// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.Localization.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using OzzCodeGen.Definitions;
    using OzzCodeGen.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class LocalizationResx : AbstractTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<root>\r\n  <xsd:schema id=\"root\" xmlns=\"\" " +
                    "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:msdata=\"urn:schemas-microsoft" +
                    "-com:xml-msdata\">\r\n    <xsd:import namespace=\"http://www.w3.org/XML/1998/namespa" +
                    "ce\" />\r\n    <xsd:element name=\"root\" msdata:IsDataSet=\"true\">\r\n      <xsd:comple" +
                    "xType>\r\n        <xsd:choice maxOccurs=\"unbounded\">\r\n          <xsd:element name=" +
                    "\"metadata\">\r\n            <xsd:complexType>\r\n              <xsd:sequence>\r\n      " +
                    "          <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" />\r\n        " +
                    "      </xsd:sequence>\r\n              <xsd:attribute name=\"name\" use=\"required\" t" +
                    "ype=\"xsd:string\" />\r\n              <xsd:attribute name=\"type\" type=\"xsd:string\" " +
                    "/>\r\n              <xsd:attribute name=\"mimetype\" type=\"xsd:string\" />\r\n         " +
                    "     <xsd:attribute ref=\"xml:space\" />\r\n            </xsd:complexType>\r\n        " +
                    "  </xsd:element>\r\n          <xsd:element name=\"assembly\">\r\n            <xsd:comp" +
                    "lexType>\r\n              <xsd:attribute name=\"alias\" type=\"xsd:string\" />\r\n      " +
                    "        <xsd:attribute name=\"name\" type=\"xsd:string\" />\r\n            </xsd:compl" +
                    "exType>\r\n          </xsd:element>\r\n          <xsd:element name=\"data\">\r\n        " +
                    "    <xsd:complexType>\r\n              <xsd:sequence>\r\n                <xsd:elemen" +
                    "t name=\"value\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"1\" />\r\n          " +
                    "      <xsd:element name=\"comment\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal" +
                    "=\"2\" />\r\n              </xsd:sequence>\r\n              <xsd:attribute name=\"name\"" +
                    " type=\"xsd:string\" use=\"required\" msdata:Ordinal=\"1\" />\r\n              <xsd:attr" +
                    "ibute name=\"type\" type=\"xsd:string\" msdata:Ordinal=\"3\" />\r\n              <xsd:at" +
                    "tribute name=\"mimetype\" type=\"xsd:string\" msdata:Ordinal=\"4\" />\r\n              <" +
                    "xsd:attribute ref=\"xml:space\" />\r\n            </xsd:complexType>\r\n          </xs" +
                    "d:element>\r\n          <xsd:element name=\"resheader\">\r\n            <xsd:complexTy" +
                    "pe>\r\n              <xsd:sequence>\r\n                <xsd:element name=\"value\" typ" +
                    "e=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"1\" />\r\n              </xsd:sequence" +
                    ">\r\n              <xsd:attribute name=\"name\" type=\"xsd:string\" use=\"required\" />\r" +
                    "\n            </xsd:complexType>\r\n          </xsd:element>\r\n        </xsd:choice>" +
                    "\r\n      </xsd:complexType>\r\n    </xsd:element>\r\n  </xsd:schema>\r\n  <resheader na" +
                    "me=\"resmimetype\">\r\n    <value>text/microsoft-resx</value>\r\n  </resheader>\r\n  <re" +
                    "sheader name=\"version\">\r\n    <value>2.0</value>\r\n  </resheader>\r\n    <resheader " +
                    "name=\"reader\">\r\n    <value>System.Resources.ResXResourceReader, System.Windows.F" +
                    "orms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>\r" +
                    "\n  </resheader>\r\n  <resheader name=\"writer\">\r\n    <value>System.Resources.ResXRe" +
                    "sourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyT" +
                    "oken=b77a5c561934e089</value>\r\n  </resheader>\r\n  \r\n\t<data name=\"ModelName\" xml:s" +
                    "pace=\"preserve\">\r\n\t\t<value>");
            
            #line 71 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));
            
            #line default
            #line hidden
            this.Write("</value>\r\n\t</data>\r\n\t<data name=\"ModelTitle\" xml:space=\"preserve\">\r\n\t    <value>");
            
            #line 74 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTitle));
            
            #line default
            #line hidden
            this.Write("</value>\r\n\t</data>\r\n");
            
            #line 76 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
 foreach (LocalizationPropertySetting property in EntitySetting.Properties) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t<data name=\"");
            
            #line 78 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\" xml:space=\"preserve\">\r\n\t\t<value>");
            
            #line 79 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyLabel(property)));
            
            #line default
            #line hidden
            this.Write("</value>\r\n\t</data>\r\n");
            
            #line 81 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
 if(property.LocalizeRequiredMsg){ 
            
            #line default
            #line hidden
            this.Write("\t<data name=\"");
            
            #line 82 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("RequiredMsg\" xml:space=\"preserve\">\r\n\t\t<value>");
            
            #line 83 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyRequiredMsg(property)));
            
            #line default
            #line hidden
            this.Write("</value>\r\n\t</data>\r\n");
            
            #line 85 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
 } 
            
            #line default
            #line hidden
            
            #line 86 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
 if(property.LocalizeValidationMsg){ 
            
            #line default
            #line hidden
            this.Write("\t<data name=\"");
            
            #line 87 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("ValidationMsg\" xml:space=\"preserve\">\r\n\t\t<value>");
            
            #line 88 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyValidationMsg(property)));
            
            #line default
            #line hidden
            this.Write("</value>\r\n\t</data>\r\n");
            
            #line 90 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
 } 
            
            #line default
            #line hidden
            
            #line 91 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\Localization\Templates\LocalizationResx.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</root>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
