using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;
using OzzCodeGen.CodeEngines;
using OzzCodeGen.Utilities;
using OzzUtils;

namespace OzzCodeGen.UI
{
    public abstract class AbstractEngineUI : UserControl, INotifyPropertyChanged
    {
        public AbstractEngineUI()
        {
            ColumnWidths.Add("Name", 160);
            ColumnWidths.Add("OverwriteExisting", 70);
            ColumnWidths.Add("BaseTypeName", 160);

            ReadOnlyColumns.Add("Name");

            HiddenColumns.Add("IsKey");
            HiddenColumns.Add("IsSimpleOrString");
            HiddenColumns.Add("DataModel");
            HiddenColumns.Add("EntityDefinition");
            HiddenColumns.Add("EntitySetting");
            HiddenColumns.Add("PropertyDefinition");
        }


        protected virtual void RaisePropertyChanged(string propertyName)
        {
            if (!string.IsNullOrEmpty(propertyName) && PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
        public event PropertyChangedEventHandler PropertyChanged;



        public BaseCodeEngine CodeEngine
        {
            set
            {
                _codeEngine = value;
                OnCodeEngineChanged();
            }
            get { return _codeEngine; }
        }
        BaseCodeEngine _codeEngine;
        protected virtual void OnCodeEngineChanged() { }

        public DataGrid EntitiesDataGrid { get; set; }
        public DataGrid PropertiesDataGrid { get; set; }

        protected Dictionary<string, short> ColumnWidths
        {
            get
            {
                if(_columnWidths==null)
                    _columnWidths = new Dictionary<string, short>();
                return _columnWidths;
            }
        }
        private Dictionary<string, short> _columnWidths;


        public List<string> ReadOnlyColumns
        {
            get
            {
                if (_readOnlyColumns == null)
                    _readOnlyColumns = new List<string>();
                return _readOnlyColumns;
            }
        }
        private List<string> _readOnlyColumns;


        public List<string> HiddenColumns
        {
            get
            {
                if (_hiddenColumns == null)
                    _hiddenColumns = new List<string>();
                return _hiddenColumns;
            }
        }
        private List<string> _hiddenColumns;




        protected void SetColumns(DataGrid dataGrid)
        {
            foreach (DataGridColumn c in dataGrid.Columns)
            {
                c.IsReadOnly = ReadOnlyColumns.Contains(c.Header.ToString());
                if (ColumnWidths.ContainsKey(c.Header.ToString()))
                    c.Width = ColumnWidths[c.Header.ToString()];

                c.Header = c.Header.ToString().PascalCaseToTitleCase();
            }
            int i = 0;
            DataGridTools.ReorderDataGridColumn(dataGrid, "Name", i);
            i++;
            DataGridTools.ReorderDataGridColumn(dataGrid, "Exclude", i);
        }



        protected void btnRefresh_Click(object sender, RoutedEventArgs e)
        {
            int i = EntitiesDataGrid.SelectedIndex;
            CodeEngine.RefreshFromProject(true);

            if (EntitiesDataGrid.Items.Count > i)
                EntitiesDataGrid.SelectedIndex = i;
        }

        protected void btnRenderAllTemplates_Click(object sender, RoutedEventArgs e)
        {
            CodeEngine.RenderAllTemplates();
        }

        protected void btnRenderTemplate_Click(object sender, RoutedEventArgs e)
        {
            CodeEngine.RenderSelectedTemplate();
        }

        protected virtual void grdEntitySettings_AutoGeneratedColumns(object sender, EventArgs e)
        {
            SetColumns((DataGrid)sender);
        }

        protected virtual void grdEntitySettings_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            e.Cancel = HiddenColumns.Contains(e.Column.Header.ToString());
        }

        protected virtual void grdPropertySettings_AutoGeneratedColumns(object sender, EventArgs e)
        {
            SetColumns((DataGrid)sender);
        }
    }
}
