// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.CsModelClass.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using OzzCodeGen.Definitions;
    using OzzCodeGen.CodeEngines;
    using OzzCodeGen.Templates.Cs;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsModelClass\Templates\EnumExtensionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class EnumExtensionTemplate : BaseCSharpModelClassTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 9 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsModelClass\Templates\EnumExtensionTemplate.tt"
  WriteUsingNamespaces(); 
            
            #line default
            #line hidden
            this.Write(@"//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace ");
            
            #line 18 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsModelClass\Templates\EnumExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NamespaceName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// Provides extension methods for enum types, includ" +
                    "ing attribute retrieval and localized display value resolution.\r\n    /// </summa" +
                    "ry>\r\n    public static partial class ");
            
            #line 23 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsModelClass\Templates\EnumExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.EnumExtensionClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        /// <summary>\r\n        /// A generic extension method that aids " +
                    "in reflecting and retrieving any attribute that is applied to an `Enum`.\r\n      " +
                    "  /// </summary>\r\n        public static TAttribute? GetAttribute<TAttribute>(thi" +
                    "s Enum enumValue) where TAttribute : Attribute\r\n        {\r\n            var attri" +
                    "bute = enumValue.GetType()\r\n                            .GetMember(enumValue.ToS" +
                    "tring())\r\n                            .First()\r\n                            .Get" +
                    "CustomAttribute<TAttribute>();\r\n\r\n            return attribute;\r\n        }\r\n\r\n  " +
                    "      /// <summary>\r\n        /// Returns the <see cref=\"DisplayAttribute.Order\"/" +
                    "> value for an enum member,\r\n        /// or <see cref=\"int.MaxValue\"/> when no <" +
                    "c>[Display(Order = ...)]</c> attribute is present.\r\n        /// </summary>\r\n    " +
                    "    public static int GetDisplayOrder(Enum value)\r\n        {\r\n            var fi" +
                    "eld = value.GetType().GetField(value.ToString());\r\n            if (field == null" +
                    ")\r\n                return int.MaxValue;\r\n\r\n            return field.GetCustomAtt" +
                    "ribute<DisplayAttribute>()?.GetOrder() ?? int.MaxValue;\r\n        }\r\n\r\n        //" +
                    "/ <summary>\r\n        /// Gets the display value for an enum member from its Disp" +
                    "layAttribute.\r\n        /// </summary>\r\n        /// <param name=\"value\">The enum " +
                    "value.</param>\r\n        /// <returns>The display name from DisplayAttribute reso" +
                    "urces if available, the DisplayAttribute Name, or the enum\'s\r\n        /// string" +
                    " representation.</returns>\r\n        public static string GetDisplayValue(this En" +
                    "um value)\r\n        {\r\n            var fieldInfo = value.GetType().GetField(value" +
                    ".ToString());\r\n\r\n            if (fieldInfo == null)\r\n                return valu" +
                    "e.ToString();\r\n\r\n            DisplayAttribute[] descriptionAttributes = fieldInf" +
                    "o.GetCustomAttributes(\r\n                                                        " +
                    "         typeof(DisplayAttribute),\r\n                                            " +
                    "                     false) as DisplayAttribute[] ?? [];\r\n            if (descri" +
                    "ptionAttributes.Length > 0 && descriptionAttributes[0].ResourceType != null)\r\n  " +
                    "          {\r\n                return LookupResource(descriptionAttributes[0].Reso" +
                    "urceType!, descriptionAttributes[0].Name ?? string.Empty);\r\n            }\r\n\r\n   " +
                    "         return (descriptionAttributes.Length > 0) ? descriptionAttributes[0].Na" +
                    "me ?? value.ToString() : value.ToString();\r\n        }\r\n        \r\n        /// <su" +
                    "mmary>\r\n        /// Gets all values of the specified enum type with their displa" +
                    "y values, sorted by\r\n        /// <see cref=\"DisplayAttribute.Order\"/> when prese" +
                    "nt on the enum members.\r\n        /// </summary>\r\n        /// <remarks>\r\n        " +
                    "/// Members without a <c>[Display(Order = ...)]</c> attribute default to <c>int." +
                    "MaxValue</c>\r\n        /// so they appear after explicitly ordered members. Membe" +
                    "rs with the same order value retain\r\n        /// their declaration order (stable" +
                    " sort).\r\n        /// Use this instead of <see cref=\"GetValues{T}\"/> when enum me" +
                    "mbers carry\r\n        /// <c>[Display(Order = ...)]</c> and the UI should respect" +
                    " that order.\r\n        /// </remarks>\r\n        /// <typeparam name=\"T\">The enum t" +
                    "ype whose values to retrieve.</typeparam>\r\n        /// <returns>\r\n        /// A " +
                    "collection of <see cref=\"EnumValueItem{T}\"/> sorted by <see cref=\"DisplayAttribu" +
                    "te.Order\"/>.\r\n        /// </returns>\r\n        public static IEnumerable<EnumValu" +
                    "eItem<T>> GetOrderedValues<T>() where T : Enum\r\n        {\r\n            return Ge" +
                    "tValues<T>().OrderBy(x => GetDisplayOrder(x.Value));\r\n        }\r\n\r\n        /// <" +
                    "summary>\r\n        /// Gets all values of the specified enum type with their disp" +
                    "lay values.\r\n        /// </summary>\r\n        /// <typeparam name=\"T\">The enum ty" +
                    "pe whose values to retrieve.</typeparam>\r\n        /// <returns>A collection of e" +
                    "num value items containing each enum value and its display representation.</retu" +
                    "rns>\r\n        public static IEnumerable<EnumValueItem<T>> GetValues<T>() where T" +
                    " : Enum\r\n        {\r\n            return Enum.GetValues(typeof(T)).Cast<T>().Selec" +
                    "t(x => new EnumValueItem<T>\r\n            {\r\n                Value = x,\r\n        " +
                    "        DisplayValue = x.GetDisplayValue()\r\n            });\r\n        }\r\n\r\n      " +
                    "  private static string LookupResource(Type? resourceManagerProvider, string res" +
                    "ourceKey)\r\n        {\r\n            if (resourceManagerProvider == null)\r\n        " +
                    "        return resourceKey;\r\n\r\n            foreach (PropertyInfo staticProperty " +
                    "in resourceManagerProvider.GetProperties(BindingFlags.Static | BindingFlags.NonP" +
                    "ublic | BindingFlags.Public))\r\n            {\r\n                if (staticProperty" +
                    ".PropertyType == typeof(ResourceManager))\r\n                {\r\n                  " +
                    "  var resourceManager = (ResourceManager?)staticProperty.GetValue(null, null);\r\n" +
                    "                    return resourceManager?.GetString(resourceKey) ?? resourceKe" +
                    "y;\r\n                }\r\n            }\r\n\r\n            return resourceKey; // Fallb" +
                    "ack with the key name\r\n        }\r\n    }\r\n\r\n    /// <summary>\r\n    /// Represents" +
                    " a strongly typed enumeration value and its associated display text for use in U" +
                    "I selection or display\r\n    /// scenarios.\r\n    /// </summary>\r\n    /// <remarks" +
                    ">This class is commonly used to bind enumeration values to user interface elemen" +
                    "ts, such as\r\n    /// dropdown lists or combo boxes, where both the underlying va" +
                    "lue and a user-friendly display string are\r\n    /// needed.</remarks>\r\n    /// <" +
                    "typeparam name=\"T\">The enumeration type represented by this item.</typeparam>\r\n " +
                    "   public class EnumValueItem<T> where T : Enum\r\n    {\r\n        public required " +
                    "T Value { get; set; }\r\n        public string DisplayValue { get; set; } = string" +
                    ".Empty;\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
