using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OzzUtils;

namespace OzzCodeGen
{
    public class PropertyDefaultSetting : INotifyPropertyChanged
    {
        /// <summary>
        /// Name of the entity
        /// </summary>
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name == value) return;
                _name = value;
                RaisePropertyChanged("Name");
            }
        }
        private string _name;

        public bool Exclude
        {
            get { return _exclude; }
            set
            {
                if (_exclude == value) return;
                _exclude = value;
                RaisePropertyChanged("Exclude");
            }
        }
        private bool _exclude;


        /// <summary>
        /// Display order for UI
        /// </summary>

        public int DisplayOrder
        {
            get { return displayOrder; }
            set
            {
                if (displayOrder == value) return;
                displayOrder = value;
                RaisePropertyChanged("DisplayOrder");
            }
        }
        private int displayOrder;


        /// <summary>
        /// Display text for UI
        /// </summary>
        public string DisplayName
        {
            get
            {
                if (string.IsNullOrEmpty(displayName))
                {
                    displayName = Name.ToTitleCase();
                }
                return displayName;
            }
            set { displayName = value; }
        }
        string displayName;


        public bool Editable
        {
            get { return _editable; }
            set
            {
                if (_editable == value) return;
                _editable = value;
                RaisePropertyChanged("Editable");
            }
        }
        private bool _editable;

        public bool IsNullable
        {
            get { return isNullable; }
            set
            {
                if (isNullable == value) return;
                isNullable = value;
                RaisePropertyChanged("IsNullable");
            }
        }
        private bool isNullable;

        public bool UiVisible
        {
            get { return _uiVisible; }
            set
            {
                if (_uiVisible == value) return;
                _uiVisible = value;
                RaisePropertyChanged("UiVisible");
            }
        }
        private bool _uiVisible;

        /// <summary>
        /// If the value computed or generated by dabatbase retuns true
        /// </summary>
        public bool IsStoreGenerated
        {
            get { return isStoreGenerated; }
            set
            {
                if (isStoreGenerated == value) return;
                isStoreGenerated = value;
                RaisePropertyChanged("IsStoreGenerated");
            }
        }
        private bool isStoreGenerated;


        public override string ToString()
        {
            return Name;
        }



        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void RaisePropertyChanged(string propertyName)
        {
            if (!string.IsNullOrEmpty(propertyName) && PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
