namespace OzzCodeGen.CodeEngines.WpfMvvm.Templates;

public class MvvmBaseClassesTemplate : AbstractTemplate
{
    private readonly WpfMvvmCodeEngine _codeEngine;

    public MvvmBaseClassesTemplate(WpfMvvmCodeEngine codeEngine)
    {
        _codeEngine = codeEngine;
    }

    public override string GetDefaultFileName()
    {
        return "ViewModelBase.cs";
    }

    public override string TransformText()
    {
        return "using System;\n"
             + "using System.Collections.Generic;\n"
             + "using System.ComponentModel;\n"
             + "using System.Runtime.CompilerServices;\n"
             + "using System.Threading.Tasks;\n"
             + "using System.Windows.Input;\n"
             + $"using {_codeEngine.ContractsNamespaceName};\n\n"
             + $"namespace {_codeEngine.BaseClassNamespaceName};\n\n"
             + "public abstract class ViewModelBase : INotifyPropertyChanged, IViewModel\n"
             + "{\n"
             + "    public event PropertyChangedEventHandler PropertyChanged;\n\n"
             + "    protected bool SetProperty<T>(ref T storage, T value, [CallerMemberName] string propertyName = null)\n"
             + "    {\n"
             + "        if (EqualityComparer<T>.Default.Equals(storage, value))\n"
             + "        {\n"
             + "            return false;\n"
             + "        }\n\n"
             + "        storage = value;\n"
             + "        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));\n"
             + "        return true;\n"
             + "    }\n\n"
             + "    public Task InitializeAsync(object parameter = null)\n"
             + "    {\n"
             + "        return OnInitializeAsync(parameter);\n"
             + "    }\n\n"
             + "    protected virtual Task OnInitializeAsync(object parameter)\n"
             + "    {\n"
             + "        return Task.CompletedTask;\n"
             + "    }\n"
             + "}\n\n"
             + "public class RelayCommand : ICommand\n"
             + "{\n"
             + "    private readonly Action _execute;\n"
             + "    private readonly Func<bool> _canExecute;\n\n"
             + "    public RelayCommand(Action execute, Func<bool> canExecute = null)\n"
             + "    {\n"
             + "        _execute = execute ?? throw new ArgumentNullException(nameof(execute));\n"
             + "        _canExecute = canExecute;\n"
             + "    }\n\n"
             + "    public event EventHandler CanExecuteChanged;\n\n"
             + "    public bool CanExecute(object parameter)\n"
             + "    {\n"
             + "        return _canExecute?.Invoke() ?? true;\n"
             + "    }\n\n"
             + "    public void Execute(object parameter)\n"
             + "    {\n"
             + "        _execute();\n"
             + "    }\n\n"
             + "    public void RaiseCanExecuteChanged()\n"
             + "    {\n"
             + "        CanExecuteChanged?.Invoke(this, EventArgs.Empty);\n"
             + "    }\n"
             + "}\n\n"
             + "public class AsyncRelayCommand : IAsyncCommand\n"
             + "{\n"
             + "    private readonly Func<Task> _executeAsync;\n"
             + "    private readonly Func<bool> _canExecute;\n"
             + "    private bool _isExecuting;\n\n"
             + "    public AsyncRelayCommand(Func<Task> executeAsync, Func<bool> canExecute = null)\n"
             + "    {\n"
             + "        _executeAsync = executeAsync ?? throw new ArgumentNullException(nameof(executeAsync));\n"
             + "        _canExecute = canExecute;\n"
             + "    }\n\n"
             + "    public event EventHandler CanExecuteChanged;\n\n"
             + "    public bool CanExecute(object parameter)\n"
             + "    {\n"
             + "        return !_isExecuting && (_canExecute?.Invoke() ?? true);\n"
             + "    }\n\n"
             + "    public async void Execute(object parameter)\n"
             + "    {\n"
             + "        await ExecuteAsync(parameter);\n"
             + "    }\n\n"
             + "    public async Task ExecuteAsync(object parameter = null)\n"
             + "    {\n"
             + "        if (!CanExecute(parameter))\n"
             + "        {\n"
             + "            return;\n"
             + "        }\n\n"
             + "        _isExecuting = true;\n"
             + "        RaiseCanExecuteChanged();\n"
             + "        try\n"
             + "        {\n"
             + "            await _executeAsync();\n"
             + "        }\n"
             + "        finally\n"
             + "        {\n"
             + "            _isExecuting = false;\n"
             + "            RaiseCanExecuteChanged();\n"
             + "        }\n"
             + "    }\n\n"
             + "    public void RaiseCanExecuteChanged()\n"
             + "    {\n"
             + "        CanExecuteChanged?.Invoke(this, EventArgs.Empty);\n"
             + "    }\n"
             + "}\n";
    }
}
