// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.WpfMvvm.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using OzzCodeGen.Definitions;
    using OzzCodeGen.CodeEngines;
    using OzzCodeGen.Templates.Cs;
    using OzzCodeGen.CodeEngines.Mvvm;
    using OzzUtils;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class WpfViewModelTemplate : BaseCSharpWpfMvvmTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 11 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"

    var properties = GetIncludedProperties().ToList();
    var foreignLookupEntities = GetForeignLookupEntities();
    var enumTypeNames = GetEnumTypeNames().ToList();
    WriteUsingNamespaces(); 
            
            #line default
            #line hidden
            this.Write(@"//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace ");
            
            #line 24 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.GetViewModelsNamespaceName()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial class ");
            
            #line 26 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetClassName()));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 26 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetBaseClassName()));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 28 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  if (TemplateType == MvvmTemplate.Collection) {
        string queryParamsName = EntitySetting.GenerateGetPaged ? "queryParams" : string.Empty;
        var pkey = GetPrimaryKey();  
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 31 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetClassName()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 31 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVmConstructorParams(isDeclaration: true)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            ");
            
            #line 33 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.RepositoryInstanceName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 33 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.RepositoryInstanceName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n            ");
            
            #line 34 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write(" = new ObservableCollection<");
            
            #line 34 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n\r\n            ");
            
            #line 36 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("CreateCommand = new ");
            
            #line 36 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("CreateCommand (");
            
            #line 36 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCommandConstructorParams("this", templateType: MvvmTemplate.Create, hasDlgService:true)));
            
            #line default
            #line hidden
            this.Write(");\r\n            ");
            
            #line 37 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("DeleteCommand = new ");
            
            #line 37 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("DeleteCommand (");
            
            #line 37 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCommandConstructorParams("this", templateType: MvvmTemplate.Delete)));
            
            #line default
            #line hidden
            this.Write(");\r\n            ");
            
            #line 38 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("EditCommand = new ");
            
            #line 38 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("EditCommand (");
            
            #line 38 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCommandConstructorParams("this", templateType: MvvmTemplate.Edit, hasDlgService:true)));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        public ");
            
            #line 41 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.RepositoryName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 41 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.RepositoryInstanceName));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n        public ObservableCollection<");
            
            #line 42 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 42 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n\r\n        public ");
            
            #line 44 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("CreateCommand ");
            
            #line 44 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("CreateCommand { get; }\r\n        public ");
            
            #line 45 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("DeleteCommand ");
            
            #line 45 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("DeleteCommand { get; }\r\n        public ");
            
            #line 46 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("EditCommand ");
            
            #line 46 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("EditCommand { get; }\r\n\r\n");
            
            #line 48 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
      if (EntitySetting.GenerateGetPaged) { 
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 49 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.GetQueryParamClassName()));
            
            #line default
            #line hidden
            this.Write("? LastQueryParams { get; private set; }\r\n\r\n        public async Task Load");
            
            #line 51 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("Async()\r\n        {\r\n            await Load");
            
            #line 53 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("Async(LastQueryParams ?? new ");
            
            #line 53 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.GetQueryParamClassName()));
            
            #line default
            #line hidden
            this.Write("());\r\n        }\r\n\r\n        public async Task Load");
            
            #line 56 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 56 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.GetQueryParamClassName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 56 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryParamsName));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 57 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
      } else { 
            
            #line default
            #line hidden
            this.Write("        public async Task Load");
            
            #line 58 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("Async()\r\n");
            
            #line 59 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
      } 
            
            #line default
            #line hidden
            this.Write("        {\r\n            if (Load");
            
            #line 61 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("InProgress)\r\n                return;\r\n            Load");
            
            #line 63 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("InProgress = true;\r\n");
            
            #line 64 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
      if (EntitySetting.GenerateGetPaged) { 
            
            #line default
            #line hidden
            this.Write("            var items = await ");
            
            #line 65 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.RepositoryInstanceName));
            
            #line default
            #line hidden
            this.Write(".GetPagedAsync(");
            
            #line 65 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryParamsName));
            
            #line default
            #line hidden
            this.Write(");\r\n            LastQueryParams = ");
            
            #line 66 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryParamsName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 67 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
      } else { 
            
            #line default
            #line hidden
            this.Write("            var items = await ");
            
            #line 68 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.RepositoryInstanceName));
            
            #line default
            #line hidden
            this.Write(".GetAllAsync();\r\n");
            
            #line 69 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
      } 
            
            #line default
            #line hidden
            this.Write("            ReplaceCollection(");
            
            #line 70 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write(", items);\r\n            Load");
            
            #line 71 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("InProgress = false;\r\n            On");
            
            #line 72 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("Loaded();\r\n        }\r\n        public bool Load");
            
            #line 74 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("InProgress { get; private set; } = false;\r\n        protected virtual void On");
            
            #line 75 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("Loaded() { /* For override in derived classes */ }\r\n        \r\n\r\n        public as" +
                    "ync Task Save");
            
            #line 78 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 78 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 78 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (");
            
            #line 80 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 80 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkey.Name));
            
            #line default
            #line hidden
            this.Write(" <= 0)\r\n                ");
            
            #line 81 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 81 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkey.Name));
            
            #line default
            #line hidden
            this.Write(" = await ");
            
            #line 81 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.RepositoryInstanceName));
            
            #line default
            #line hidden
            this.Write(".CreateAsync(");
            
            #line 81 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            else\r\n                await ");
            
            #line 83 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.RepositoryInstanceName));
            
            #line default
            #line hidden
            this.Write(".UpdateAsync(");
            
            #line 83 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        public ");
            
            #line 86 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("? Selected");
            
            #line 86 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get { return SelectedItem; }\r\n            set\r\n         " +
                    "   {\r\n                SelectedItem = value;\r\n                RaisePropertyChange" +
                    "d(nameof(Selected");
            
            #line 92 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("));\r\n            }\r\n        }\r\n");
            
            #line 95 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
      WriteLine("    }");
        WriteLine("}");
        return this.GenerationEnvironment.ToString();
    } 
            
            #line default
            #line hidden
            
            #line 99 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  foreach (var lookupEntity in foreignLookupEntities) { 
            
            #line default
            #line hidden
            this.Write("        private readonly ");
            
            #line 100 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.GetLookupName(LookupTemplate.Interface)));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 100 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.GetLookupName(LookupTemplate.RunTimeClass).ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 101 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("        private ");
            
            #line 102 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 102 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n        public ");
            
            #line 103 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 103 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write(" => _");
            
            #line 103 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n        public ");
            
            #line 105 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetClassName()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 105 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetVmConstructorParams(isDeclaration: true)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 107 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  foreach (var lookupEntity in foreignLookupEntities) { 
            
            #line default
            #line hidden
            this.Write("            _");
            
            #line 108 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.GetLookupName(LookupTemplate.RunTimeClass).ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 108 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.GetLookupName(LookupTemplate.RunTimeClass).ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n            ");
            
            #line 109 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write(" = new ObservableCollection<");
            
            #line 109 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n\r\n");
            
            #line 111 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 112 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  foreach (var enumTypeName in enumTypeNames) { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 113 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumTypeName));
            
            #line default
            #line hidden
            this.Write("Values = GetValues<");
            
            #line 113 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumTypeName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\r\n");
            
            #line 115 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 116 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  if (IsEdit) { 
            
            #line default
            #line hidden
            this.Write("            _");
            
            #line 117 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 117 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 118 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("            _");
            
            #line 119 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 119 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 120 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
      foreach (var prop in EntitySetting.GetDefaultValuedProperties()) {
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 121 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 121 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.FormatDefaultValue()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 122 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
    } 
            
            #line default
            #line hidden
            
            #line 123 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("            OnInitialized();\r\n        }\r\n        partial void OnInitialized();\r\n");
            
            #line 127 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  foreach (var lookupEntity in foreignLookupEntities) { 
            
            #line default
            #line hidden
            this.Write("\r\n        public ObservableCollection<");
            
            #line 129 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 129 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n\r\n        public async Task Load");
            
            #line 131 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("Async()\r\n        {\r\n            var items = await _");
            
            #line 133 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.GetLookupName(LookupTemplate.RunTimeClass).ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".Get");
            
            #line 133 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 133 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.HasIsActiveProperty() ? "isActive: true" : ""));
            
            #line default
            #line hidden
            this.Write(");\r\n            ");
            
            #line 134 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write(".Clear();\r\n            foreach (var item in items)\r\n            {\r\n              " +
                    "  ");
            
            #line 137 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lookupEntity.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write(".Add(item);\r\n            }\r\n        }\r\n");
            
            #line 140 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 141 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  foreach (var enumTypeName in enumTypeNames) { 
            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// Gets the collection of available ");
            
            #line 144 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumTypeName));
            
            #line default
            #line hidden
            this.Write(" enum members for selection or display.\r\n        /// </summary>\r\n        public I" +
                    "Enumerable<EnumValueItem<");
            
            #line 146 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumTypeName));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 146 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumTypeName));
            
            #line default
            #line hidden
            this.Write("Values { get; }\r\n");
            
            #line 147 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 148 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  foreach (var prop in properties.Where(p => !p.IsKey))
    {
        bool isReadOnly = IsEdit ? prop.IsReadOnlyInEdit : prop.IsReadOnlyInCreate;

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 153 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
      if (isReadOnly) { 
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 154 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.GetTypeName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 154 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(" => _");
            
            #line 154 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 154 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 155 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
      } else { 
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 156 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.GetTypeName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 156 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get { return _");
            
            #line 158 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 158 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n            set\r\n            {\r\n");
            
            #line 161 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
          if (prop.IsNullableString) { 
            
            #line default
            #line hidden
            this.Write("                if (!string.IsNullOrWhiteSpace(value) && _");
            
            #line 162 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 162 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(" != value)\r\n");
            
            #line 163 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
          } else { 
            
            #line default
            #line hidden
            this.Write("                if (_");
            
            #line 164 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 164 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(" != value)\r\n");
            
            #line 165 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
          } 
            
            #line default
            #line hidden
            this.Write("                {\r\n                    _");
            
            #line 167 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 167 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(" = value");
            
            #line 167 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.ValueConstraint));
            
            #line default
            #line hidden
            this.Write(";\r\n                    RaisePropertyChanged(nameof(");
            
            #line 168 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write("));\r\n                    ValidateProperty(_");
            
            #line 169 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", nameof(");
            
            #line 169 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write("));\r\n                }\r\n");
            
            #line 171 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
          if (prop.IsNullableString) { 
            
            #line default
            #line hidden
            this.Write("                else if (string.IsNullOrWhiteSpace(value))\r\n                {\r\n  " +
                    "                  _");
            
            #line 174 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 174 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n                    RaisePropertyChanged(nameof(");
            
            #line 175 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write("));\r\n                    ValidateProperty(_");
            
            #line 176 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", nameof(");
            
            #line 176 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write("));\r\n                }\r\n");
            
            #line 178 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
          } 
            
            #line default
            #line hidden
            this.Write("            }\r\n        }\r\n");
            
            #line 181 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
      } 
            
            #line default
            #line hidden
            
            #line 182 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\r\n        public bool ValidateModel()\r\n        {\r\n            return ValidateMode" +
                    "l(_");
            
            #line 186 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\WpfMvvm\Templates\WpfViewModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
