// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.Storage.Templates.MsSql
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class TsqlStoredProcs : AbstractStorageTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("SET ANSI_NULLS ON\r\nGo\r\nSET QUOTED_IDENTIFIER ON\r\nGo\r\n\r\n");
            
            #line 12 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  var firstBase = TableDefinition.GetFirstBase();
    string pkeyVal = "@" + firstBase.PrimaryKeyColumn.Name;
    var deleteMarkColumn = firstBase.GetDeleteMarkColumn();
    bool createInsertOrUpdate = TableDefinition.StoredProcInsertOrUpdate;
    string logInsSP = string.Concat("[", CodeEngine.LogSchemaName, "].[", TableDefinition.LogTableName, "_Insert]");

            
            #line default
            #line hidden
            
            #line 18 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  if(TableDefinition.HasLogTable) { 
            
            #line default
            #line hidden
            this.Write("-- --------------------------------------------------------------------\r\n-- Store" +
                    "d Procedure: ");
            
            #line 20 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(logInsSP));
            
            #line default
            #line hidden
            this.Write("\r\n-- --------------------------------------------------------------------\r\nIF  EX" +
                    "ISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'");
            
            #line 22 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(logInsSP));
            
            #line default
            #line hidden
            this.Write("\') AND type in (N\'P\', N\'PC\'))\r\nDROP PROCEDURE ");
            
            #line 23 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(logInsSP));
            
            #line default
            #line hidden
            this.Write("\r\nGo\r\nCREATE PROCEDURE ");
            
            #line 25 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(logInsSP));
            
            #line default
            #line hidden
            this.Write("\r\n    @");
            
            #line 26 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.Name));
            
            #line default
            #line hidden
            this.Write("Id ");
            
            #line 26 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetColumnType(TableDefinition.PrimaryKeyColumn)));
            
            #line default
            #line hidden
            this.Write(",\r\n    @LogStatus [int],\r\n    @LogStatusDescription [nVarChar](100)\r\nAs\r\nBegin\r\n " +
                    "   Insert Into [");
            
            #line 31 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.LogSchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 31 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.LogTableName));
            
            #line default
            #line hidden
            this.Write("](\r\n            [");
            
            #line 32 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.Name));
            
            #line default
            #line hidden
            this.Write("Id],\r\n");
            
            #line 33 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  var columns = TableDefinition.GetColumnList().Where(c => c.PrimaryKey == false & c.DoNotLog == false & c.Exclude == false);
    foreach (var column in columns)
    {
            
            #line default
            #line hidden
            this.Write("            [");
            
            #line 36 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("],\r\n");
            
            #line 37 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  } 
            
            #line default
            #line hidden
            this.Write("            [LogStatus], \r\n            [LogStatusDescription])\r\n    Select  [");
            
            #line 40 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.PrimaryKeyColumn.Name));
            
            #line default
            #line hidden
            this.Write("],\r\n");
            
            #line 41 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  foreach (var column in columns)
    {
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 43 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.GetLogParam()));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 44 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  } 
            
            #line default
            #line hidden
            this.Write("            @LogStatus,\r\n            @LogStatusDescription\r\n    From  ");
            
            #line 47 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.ConcatTableNameAndSchema()));
            
            #line default
            #line hidden
            this.Write("\r\n    Where ");
            
            #line 48 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.ConcatTableNameAndSchema()));
            
            #line default
            #line hidden
            this.Write(".[");
            
            #line 48 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.PrimaryKeyColumn.Name));
            
            #line default
            #line hidden
            this.Write("] = @");
            
            #line 48 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.Name));
            
            #line default
            #line hidden
            this.Write("Id;\r\nEnd\r\nGo\r\n");
            
            #line 51 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  } 
            
            #line default
            #line hidden
            this.Write("-- --------------------------------------------------------------------\r\n-- Store" +
                    "d Procedure: [");
            
            #line 53 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 53 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_Delete]\r\n-- --------------------------------------------------------------------" +
                    "\r\nIF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[");
            
            #line 55 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 55 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_Delete]\') AND type in (N\'P\', N\'PC\'))\r\nDROP PROCEDURE [");
            
            #line 56 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 56 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_Delete]\r\nGo\r\nCREATE PROCEDURE [");
            
            #line 58 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 58 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_Delete]\r\n    ");
            
            #line 59 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkeyVal));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 59 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetColumnType(firstBase.PrimaryKeyColumn)));
            
            #line default
            #line hidden
            this.Write("\r\nAs\r\nBegin\r\n");
            
            #line 62 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  if(TableDefinition.HasLogTable) { 
            
            #line default
            #line hidden
            this.Write("    /* Silinmeden önceki son hali loglanıyor... */\r\n    Exec ");
            
            #line 64 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(logInsSP));
            
            #line default
            #line hidden
            this.Write("\r\n        @");
            
            #line 65 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.Name));
            
            #line default
            #line hidden
            this.Write("Id = ");
            
            #line 65 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkeyVal));
            
            #line default
            #line hidden
            this.Write(",\r\n        @LogStatus = 4010,\r\n        @LogStatusDescription = N\'Siliniyor...\';\r\n" +
                    "\r\n");
            
            #line 69 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  } 
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"

if(deleteMarkColumn != null)
{
 
            
            #line default
            #line hidden
            this.Write("    Declare @");
            
            #line 74 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deleteMarkColumn.Name));
            
            #line default
            #line hidden
            this.Write(" bit;\r\n\r\n    Select @");
            
            #line 76 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deleteMarkColumn.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 76 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deleteMarkColumn.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        From [");
            
            #line 77 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 77 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.TableName));
            
            #line default
            #line hidden
            this.Write("]\r\n        Where ");
            
            #line 78 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.PrimaryKeyColumn));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 78 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkeyVal));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n    If @");
            
            #line 80 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deleteMarkColumn.Name));
            
            #line default
            #line hidden
            this.Write(" = 1\r\n    Begin\r\n        /* TODO: Check cascaded data from other tables */\r\n");
            
            #line 83 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  PushIndent("    ");
    WriteDeleteStatement(TableDefinition, firstBase, pkeyVal);
    PopIndent(); 
            
            #line default
            #line hidden
            this.Write("        \r\n    End\r\n    Else\r\n    Begin\r\n        Update [");
            
            #line 90 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 90 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.TableName));
            
            #line default
            #line hidden
            this.Write("]\r\n            Set ");
            
            #line 91 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deleteMarkColumn.Name));
            
            #line default
            #line hidden
            this.Write(" = 1\r\n            Where [");
            
            #line 92 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.PrimaryKeyColumn));
            
            #line default
            #line hidden
            this.Write("] = ");
            
            #line 92 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkeyVal));
            
            #line default
            #line hidden
            this.Write("\r\n    End\r\n");
            
            #line 94 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    } else { 
            
            #line default
            #line hidden
            this.Write("    /* TODO: Check cascaded data from other tables */\r\n");
            
            #line 96 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 WriteDeleteStatement(TableDefinition, firstBase, pkeyVal); 
            
            #line default
            #line hidden
            
            #line 97 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"

} 
            
            #line default
            #line hidden
            this.Write("End\r\nGo\r\n-- --------------------------------------------------------------------\r" +
                    "\n-- Stored Procedure: [");
            
            #line 102 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 102 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_Insert]\r\n-- --------------------------------------------------------------------" +
                    "\r\nIF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[");
            
            #line 104 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 104 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_Insert]\') AND type in (N\'P\', N\'PC\'))\r\nDROP PROCEDURE [");
            
            #line 105 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 105 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_Insert]\r\nGo\r\nCREATE PROCEDURE [");
            
            #line 107 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 107 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_Insert]\r\n");
            
            #line 108 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
        
    var colDeclaresIns = TableDefinition.GetColumnList().Where(c => c.PrimaryKey == false && !c.DataType.StartsWith("as ", StringComparison.InvariantCultureIgnoreCase) && c.Exclude == false & string.IsNullOrEmpty(c.InsertDefault));
    int colNr = 0;
    foreach (var column in colDeclaresIns)
    { 
            colNr++;
            
            #line default
            #line hidden
            this.Write("    @");
            
            #line 114 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 114 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetColumnType(column)));
            
            #line default
            #line hidden
            
            #line 114 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 if(colNr < colDeclaresIns.Count()) {
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 114 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  } 
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 115 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    } 
            
            #line default
            #line hidden
            this.Write("As\r\nBegin\r\n    Declare @newKey        ");
            
            #line 118 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.PrimaryKeyColumn.DataType));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 120 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 WriteInsertStatement(firstBase, string.Empty); 
            
            #line default
            #line hidden
            this.Write("\r\n    Set @newKey = SCOPE_IDENTITY();\r\n");
            
            #line 123 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  if(TableDefinition.HasLogTable) { 
            
            #line default
            #line hidden
            this.Write("    Exec ");
            
            #line 124 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(logInsSP));
            
            #line default
            #line hidden
            this.Write("\r\n        @");
            
            #line 125 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.Name));
            
            #line default
            #line hidden
            this.Write("Id = @newKey,\r\n        @LogStatus = 1010,\r\n        @LogStatusDescription = N\'Yeni" +
                    " Kayıt\';\r\n");
            
            #line 128 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  } 
            
            #line default
            #line hidden
            
            #line 129 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  if(TableDefinition.UseInheritance)
    { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 132 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 WriteInsertStatement(TableDefinition, "@newKey"); 
            
            #line default
            #line hidden
            
            #line 133 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 135 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 WriteSelectStatement("@newKey"); 
            
            #line default
            #line hidden
            this.Write("End\r\nGo\r\n-- --------------------------------------------------------------------\r" +
                    "\n-- Stored Procedure: [");
            
            #line 139 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 139 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_Update]\r\n-- --------------------------------------------------------------------" +
                    "\r\nIF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[");
            
            #line 141 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 141 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_Update]\') AND type in (N\'P\', N\'PC\'))\r\nDROP PROCEDURE [");
            
            #line 142 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 142 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_Update]\r\nGo\r\n");
            
            #line 144 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 
    var colDeclaresUpd = TableDefinition.GetColumnList().Where(c => c.PrimaryKey == false && c.Exclude == false && !c.DataType.StartsWith("as ", StringComparison.InvariantCultureIgnoreCase) & string.IsNullOrEmpty(c.UpdateDefault));

            
            #line default
            #line hidden
            this.Write("CREATE PROCEDURE [");
            
            #line 147 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 147 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_Update]\r\n    ");
            
            #line 148 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkeyVal));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 148 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetColumnType(firstBase.PrimaryKeyColumn)));
            
            #line default
            #line hidden
            
            #line 148 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 if(colDeclaresUpd.Any()){ 
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 148 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 149 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
        
    colNr = 0;
    foreach (var column in colDeclaresUpd)
    { 
            colNr++;
            
            #line default
            #line hidden
            this.Write("    @");
            
            #line 154 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 154 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetColumnType(column)));
            
            #line default
            #line hidden
            
            #line 154 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 if(colNr < colDeclaresUpd.Count()) {
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 154 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  } 
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 155 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    } 
            
            #line default
            #line hidden
            this.Write("As\r\nBegin\r\n");
            
            #line 158 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 WriteUpdateStatement(TableDefinition, pkeyVal); 
            
            #line default
            #line hidden
            
            #line 159 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  if(TableDefinition.UseInheritance)
    { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 162 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 WriteUpdateStatement(firstBase, pkeyVal); 
            
            #line default
            #line hidden
            
            #line 163 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 165 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  if(TableDefinition.HasLogTable) { 
            
            #line default
            #line hidden
            this.Write("    Exec ");
            
            #line 166 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(logInsSP));
            
            #line default
            #line hidden
            this.Write("\r\n        @");
            
            #line 167 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.Name));
            
            #line default
            #line hidden
            this.Write("Id = ");
            
            #line 167 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkeyVal));
            
            #line default
            #line hidden
            this.Write(",\r\n        @LogStatus = 1020,\r\n        @LogStatusDescription = N\'Genel Güncelleme" +
                    "\';\r\n\r\n");
            
            #line 171 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  } 
            
            #line default
            #line hidden
            
            #line 172 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 WriteSelectStatement(pkeyVal); 
            
            #line default
            #line hidden
            this.Write("End\r\nGo\r\n");
            
            #line 175 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 if(createInsertOrUpdate){ 
            
            #line default
            #line hidden
            this.Write("\r\n-- --------------------------------------------------------------------\r\n-- Sto" +
                    "red Procedure: [");
            
            #line 178 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 178 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_InsertOrUpdate]\r\n-- ------------------------------------------------------------" +
                    "--------\r\nIF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[");
            
            #line 180 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 180 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_InsertOrUpdate]\') AND type in (N\'P\', N\'PC\'))\r\nDROP PROCEDURE [");
            
            #line 181 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 181 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_InsertOrUpdate]\r\nGo\r\nCREATE PROCEDURE [");
            
            #line 183 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 183 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_InsertOrUpdate]\r\n    --");
            
            #line 184 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkeyVal));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 184 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetColumnType(firstBase.PrimaryKeyColumn)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 185 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
        
    colNr = 0;
    foreach (var column in colDeclaresUpd)
    { 
            colNr++;
            
            #line default
            #line hidden
            this.Write("    @");
            
            #line 190 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 190 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetColumnType(column)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 191 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    } 
            
            #line default
            #line hidden
            this.Write("    @Result int OUTPUT\r\nAs\r\nBegin\r\n    Declare ");
            
            #line 195 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkeyVal));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 195 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetColumnType(firstBase.PrimaryKeyColumn)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n    Set @Result = 0\r\n    Select ");
            
            #line 198 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkeyVal));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 198 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.PrimaryKeyColumn.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        From ");
            
            #line 199 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.ConcatTableNameAndSchema()));
            
            #line default
            #line hidden
            this.Write("\r\n        Where ");
            
            #line 200 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.PrimaryKeyColumn.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 200 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkeyVal));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n    If @Id Is Null\r\n    Begin\r\n        ");
            
            #line 204 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 WriteInsertStatement(firstBase, string.Empty); 
            
            #line default
            #line hidden
            this.Write("        Set @Result = 1\r\n    End\r\n\r\n    If (Not ");
            
            #line 208 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pkeyVal));
            
            #line default
            #line hidden
            this.Write(" Is Null)\r\n    Begin\r\n");
            
            #line 210 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 WriteUpdateStatement(TableDefinition, pkeyVal); 
            
            #line default
            #line hidden
            
            #line 211 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  if(TableDefinition.UseInheritance)
    { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 214 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 WriteUpdateStatement(firstBase, pkeyVal); 
            
            #line default
            #line hidden
            
            #line 215 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    } 
            
            #line default
            #line hidden
            this.Write("        Set @Result = -1\r\n    End\r\n    Select @Result\r\nEnd\r\nGo\r\n/*\r\nTo map in EF\r" +
                    "\n\r\n        public int InsertOrUpdate(");
            
            #line 224 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.EntityDefinition.Name));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n        {\r\n            var result = ");
            
            #line 226 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_InsertOrUpdate(\r\n                //entity.");
            
            #line 227 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.PrimaryKeyColumn));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 228 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
        
    colNr = 0;
    foreach (var column in colDeclaresUpd)
    { 
            colNr++;
            
            #line default
            #line hidden
            this.Write("                entity.");
            
            #line 233 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 234 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    } 
            
            #line default
            #line hidden
            this.Write("                new ObjectParameter(\"Result\", typeof(int)));\r\n\r\n            retur" +
                    "n result.FirstOrDefault() ?? 0;\r\n        }\r\n\r\n*/\r\n");
            
            #line 241 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 242 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 
protected void WriteDeleteStatement(StorageEntitySetting table, StorageEntitySetting baseTable,string pkeyValue)
{ 
        
        #line default
        #line hidden
        
        #line 244 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("    Delete From [");

        
        #line default
        #line hidden
        
        #line 245 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.SchemaName));

        
        #line default
        #line hidden
        
        #line 245 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 245 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.TableName));

        
        #line default
        #line hidden
        
        #line 245 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("]\r\n        Where [");

        
        #line default
        #line hidden
        
        #line 246 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.SchemaName));

        
        #line default
        #line hidden
        
        #line 246 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 246 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.TableName));

        
        #line default
        #line hidden
        
        #line 246 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 246 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.PrimaryKeyColumn.Name));

        
        #line default
        #line hidden
        
        #line 246 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("] = ");

        
        #line default
        #line hidden
        
        #line 246 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkeyValue));

        
        #line default
        #line hidden
        
        #line 246 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 247 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 if(TableDefinition.UseInheritance)
    { 
        
        #line default
        #line hidden
        
        #line 248 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("\r\n    Delete From [");

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(baseTable.SchemaName));

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(baseTable.TableName));

        
        #line default
        #line hidden
        
        #line 250 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("]\r\n        Where [");

        
        #line default
        #line hidden
        
        #line 251 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(baseTable.SchemaName));

        
        #line default
        #line hidden
        
        #line 251 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 251 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(baseTable.TableName));

        
        #line default
        #line hidden
        
        #line 251 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 251 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(baseTable.PrimaryKeyColumn.Name));

        
        #line default
        #line hidden
        
        #line 251 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("] = ");

        
        #line default
        #line hidden
        
        #line 251 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkeyValue));

        
        #line default
        #line hidden
        
        #line 251 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 252 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    } 
        
        #line default
        #line hidden
        
        #line 253 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 
} 
        
        #line default
        #line hidden
        
        #line 255 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 
protected void WriteUpdateStatement(StorageEntitySetting table, string pkeyValue, int maxLineLen = 48)
{
    var columns = table.UseInheritance ?
            table.Properties.Where(c => c.PrimaryKey == false & c.Exclude == false & c.UpdateDefault != "NeverUpdate") :
            table.GetColumnList().Where(c => c.PrimaryKey == false & c.Exclude == false & c.UpdateDefault != "NeverUpdate");
    if(columns.Any())
    {
 
        
        #line default
        #line hidden
        
        #line 263 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("    Update [");

        
        #line default
        #line hidden
        
        #line 264 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.SchemaName));

        
        #line default
        #line hidden
        
        #line 264 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 264 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.TableName));

        
        #line default
        #line hidden
        
        #line 264 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("]\r\n       Set ");

        
        #line default
        #line hidden
        
        #line 265 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    
    int colNr = 0, colLen, lineLen = 0;
    PushIndent("           ");
    foreach (var column in columns)
    { 
        string colValue = string.IsNullOrEmpty(column.UpdateDefault) ? "@" + column.Name : column.UpdateDefault.Replace("{TableName}", table.TableName);
        colLen = colValue.Length + 3 + column.Name.Length;
        lineLen += colLen;
        if(lineLen > maxLineLen && colNr > 0) { WriteLine(""); } 
        colNr++;
        
        
        #line default
        #line hidden
        
        #line 275 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("[");

        
        #line default
        #line hidden
        
        #line 276 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));

        
        #line default
        #line hidden
        
        #line 276 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("] = ");

        
        #line default
        #line hidden
        
        #line 276 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(colValue));

        
        #line default
        #line hidden
        
        #line 276 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 if(colNr < columns.Count()) {
        
        #line default
        #line hidden
        
        #line 276 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 276 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 } 
        
        #line default
        #line hidden
        
        #line 277 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    }
    PopIndent();
    WriteLine("");
 
        
        #line default
        #line hidden
        
        #line 280 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("     Where [");

        
        #line default
        #line hidden
        
        #line 281 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.SchemaName));

        
        #line default
        #line hidden
        
        #line 281 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 281 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.TableName));

        
        #line default
        #line hidden
        
        #line 281 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 281 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.PrimaryKeyColumn.Name));

        
        #line default
        #line hidden
        
        #line 281 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("] = ");

        
        #line default
        #line hidden
        
        #line 281 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkeyValue));

        
        #line default
        #line hidden
        
        #line 281 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 282 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 }
} 
        
        #line default
        #line hidden
        
        #line 284 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 
protected void WriteInsertStatement(StorageEntitySetting table, string pkeyValue, int maxLineLen = 48)
{
    var columns = table.UseInheritance ?
            table.Properties.Where(c => !c.PrimaryKey & !c.Exclude & c.InsertDefault != "null") :
            table.GetColumnList().Where(c => !c.PrimaryKey & !c.Exclude & c.InsertDefault != "null");
 
        
        #line default
        #line hidden
        
        #line 290 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("    Insert Into [");

        
        #line default
        #line hidden
        
        #line 291 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.SchemaName));

        
        #line default
        #line hidden
        
        #line 291 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 291 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.TableName));

        
        #line default
        #line hidden
        
        #line 291 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("](\r\n");

        
        #line default
        #line hidden
        
        #line 292 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 
    PushIndent("            ");
    if(!string.IsNullOrEmpty(pkeyValue)){ 
        
        #line default
        #line hidden
        
        #line 294 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("[");

        
        #line default
        #line hidden
        
        #line 294 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.PrimaryKeyColumn.Name));

        
        #line default
        #line hidden
        
        #line 294 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("], ");

        
        #line default
        #line hidden
        
        #line 294 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 } 
        
        #line default
        #line hidden
        
        #line 295 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    
    int colNr = 0, colLen, lineLen = 0;
    string colValue;
    foreach (var column in columns)
    {
        colValue = string.IsNullOrEmpty(column.InsertDefault) ? "@" + column.Name : column.InsertDefault;
        colLen = colValue.Length > column.Name.Length ? colValue.Length : column.Name.Length;
        lineLen += colLen;
        if(lineLen > maxLineLen && colNr > 0) { WriteLine(""); lineLen = colValue.Length; } 
        colNr++;
        
        
        #line default
        #line hidden
        
        #line 305 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("[");

        
        #line default
        #line hidden
        
        #line 306 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));

        
        #line default
        #line hidden
        
        #line 306 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("]");

        
        #line default
        #line hidden
        
        #line 306 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 if(colNr < columns.Count()) {
        
        #line default
        #line hidden
        
        #line 306 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 306 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  } else { 
        
        #line default
        #line hidden
        
        #line 306 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(")");

        
        #line default
        #line hidden
        
        #line 306 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  } 
        
        #line default
        #line hidden
        
        #line 307 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    }
    PopIndent();
    WriteLine("");
 
        
        #line default
        #line hidden
        
        #line 310 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("    Values (");

        
        #line default
        #line hidden
        
        #line 311 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 if(!string.IsNullOrEmpty(pkeyValue)){ 
        
        #line default
        #line hidden
        
        #line 311 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkeyValue));

        
        #line default
        #line hidden
        
        #line 311 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 311 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 } 
        
        #line default
        #line hidden
        
        #line 312 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    colNr = 0;
    PushIndent("            ");
    lineLen = 0;
    foreach (var column in columns)
    {
        colValue = string.IsNullOrEmpty(column.InsertDefault) ? "@" + column.Name : column.InsertDefault;
        colLen = colValue.Length > column.Name.Length ? colValue.Length : column.Name.Length;
        lineLen += colLen;
        if(lineLen > maxLineLen && colNr > 0) { WriteLine(""); lineLen = colValue.Length;} 
        colNr++; 
        
        #line default
        #line hidden
        
        #line 322 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(colValue));

        
        #line default
        #line hidden
        
        #line 322 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 if(colNr < columns.Count()) {
        
        #line default
        #line hidden
        
        #line 322 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 322 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  } else { 
        
        #line default
        #line hidden
        
        #line 322 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(")");

        
        #line default
        #line hidden
        
        #line 322 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
  } 
        
        #line default
        #line hidden
        
        #line 323 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 }
    PopIndent();
    WriteLine("");
 
        
        #line default
        #line hidden
        
        #line 327 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 
} 
        
        #line default
        #line hidden
        
        #line 329 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 
protected void WriteSelectStatement(string keyValue)
{
    var firstBase = TableDefinition.GetFirstBase();
 
        
        #line default
        #line hidden
        
        #line 333 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("    Select  [");

        
        #line default
        #line hidden
        
        #line 334 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.TableName));

        
        #line default
        #line hidden
        
        #line 334 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 334 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.PrimaryKeyColumn.Name));

        
        #line default
        #line hidden
        
        #line 334 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("],\r\n");

        
        #line default
        #line hidden
        
        #line 335 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 WriteSelectColumns(TableDefinition, TableDefinition.UseInheritance); 
        
        #line default
        #line hidden
        
        #line 336 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 if(TableDefinition.UseInheritance)
    {
        //TODO: Handle more than one inherited base
        WriteSelectColumns(firstBase); 
    } 
        
        #line default
        #line hidden
        
        #line 341 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 //TODO: Handle more than one inherited base
    if(TableDefinition.UseInheritance)
    { 
        
        #line default
        #line hidden
        
        #line 343 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("    From  [");

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.SchemaName));

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.TableName));

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("] Inner Join ");

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.ConcatTableNameAndSchema()));

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(" On [");

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.TableName));

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.PrimaryKeyColumn.Name));

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("] = [");

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.PrimaryKeyColumn.Name));

        
        #line default
        #line hidden
        
        #line 344 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("]\r\n");

        
        #line default
        #line hidden
        
        #line 345 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    } else { 
        
        #line default
        #line hidden
        
        #line 345 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("    From  ");

        
        #line default
        #line hidden
        
        #line 346 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.ConcatTableNameAndSchema()));

        
        #line default
        #line hidden
        
        #line 346 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 347 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    } 
        
        #line default
        #line hidden
        
        #line 347 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("    Where [");

        
        #line default
        #line hidden
        
        #line 348 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.SchemaName));

        
        #line default
        #line hidden
        
        #line 348 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 348 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.TableName));

        
        #line default
        #line hidden
        
        #line 348 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 348 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(firstBase.PrimaryKeyColumn.Name));

        
        #line default
        #line hidden
        
        #line 348 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("] = ");

        
        #line default
        #line hidden
        
        #line 348 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(keyValue));

        
        #line default
        #line hidden
        
        #line 348 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 349 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 
} 
        
        #line default
        #line hidden
        
        #line 351 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"

protected void WriteSelectColumns(StorageEntitySetting table, bool hasMore = false)
{    
    var columns = table.UseInheritance ?
            table.Properties.Where(c => c.PrimaryKey == false & c.Exclude == false) :
            table.GetColumnList().Where(c => c.PrimaryKey == false & c.Exclude == false);
    int colNr = 0;
    foreach (var column in columns)
    {
        colNr++; 
        
        #line default
        #line hidden
        
        #line 360 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("            [");

        
        #line default
        #line hidden
        
        #line 361 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(table.TableName));

        
        #line default
        #line hidden
        
        #line 361 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("].[");

        
        #line default
        #line hidden
        
        #line 361 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));

        
        #line default
        #line hidden
        
        #line 361 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write("]");

        
        #line default
        #line hidden
        
        #line 361 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 if(colNr < columns.Count() | hasMore) {
        
        #line default
        #line hidden
        
        #line 361 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(",");

        
        #line default
        #line hidden
        
        #line 361 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 } 
        
        #line default
        #line hidden
        
        #line 361 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
this.Write(" \r\n");

        
        #line default
        #line hidden
        
        #line 362 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
    }

        
        #line default
        #line hidden
        
        #line 364 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\CodeEngines\Storage\Templates\MsSql\TsqlStoredProcs.tt"
 
} 
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
