// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.AspNetMvc.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using OzzCodeGen.Templates.Cs;
    using OzzUtils;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class MvcBaseController : AbstractMvcController
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 8 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
 
var roles = CodeEngine.SecurityRoles.Where(r => !r.Equals(CodeEngine.AdminRole));
string dataContextIntance = CodeEngine.DataContextInstance;
WriteUsingNamespaces(); 
            
            #line default
            #line hidden
            this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ");
            
            #line 20 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.ControllersNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial class ");
            
            #line 22 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.BaseControllerName));
            
            #line default
            #line hidden
            
            #line 22 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
 if (!CustomFile){ 
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 22 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.BaseOfBaseController));
            
            #line default
            #line hidden
            
            #line 22 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n    {\r\n        public partial class QueryParameters\r\n        {\r\n            pu" +
                    "blic string SearchString { get; set; }\r\n            public int PageNr { get; set" +
                    "; } = 1;\r\n            public int PageSize { get; set; } = 10;\r\n            publi" +
                    "c int PageCount\r\n            {\r\n                get\r\n                {\r\n        " +
                    "            return TotalCount > 0 ? (int)Math.Ceiling(TotalCount / (double)PageS" +
                    "ize) : 0;\r\n                }\r\n            }\r\n\r\n            public int Skip\r\n    " +
                    "        {\r\n                get { return (PageNr - 1) * PageSize; }\r\n            " +
                    "}\r\n\r\n            public int TotalCount\r\n            {\r\n                get { ret" +
                    "urn _totalCount; }\r\n                set\r\n                {\r\n                    " +
                    "_totalCount = value;\r\n                    if (PageNr < 1) PageNr = 1;\r\n         " +
                    "           if (PageNr > PageCount) PageNr = PageCount;\r\n                    int " +
                    "skip = (PageNr - 1) * PageSize;\r\n                }\r\n            }\r\n            i" +
                    "nt _totalCount;\r\n        }\r\n\r\n        protected virtual void SetPagerParameters(" +
                    "QueryParameters qParams)\r\n        {\r\n            ViewBag.pageNr = qParams.PageNr" +
                    ";\r\n            ViewBag.totalCount = qParams.TotalCount;\r\n            ViewBag.pag" +
                    "eSize = qParams.PageSize;\r\n            ViewBag.pageCount = qParams.PageCount;\r\n " +
                    "       }\r\n\r\n        protected virtual async Task<bool> IsUserAdminAsync()\r\n     " +
                    "   {\r\n            if (!_isUserAdmin.HasValue)\r\n            {\r\n                _i" +
                    "sUserAdmin = Request.IsAuthenticated && \r\n                                await " +
                    "UserManager.IsInRoleAsync(UserID, SecurityRoles.Admin);\r\n            }\r\n        " +
                    "    return _isUserAdmin.Value;\r\n        }\r\n        bool? _isUserAdmin;\r\n\r\n");
            
            #line 75 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
  foreach (var role in roles)
        { 
        string varName = "_" + IsUserInRoleMethods[role.Trim()].ToCamelCase();
 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n        protected virtual async Task<bool> ");
            
            #line 81 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(IsUserInRoleMethods[role.Trim()]));
            
            #line default
            #line hidden
            this.Write("Async()\r\n        {\r\n            if (!");
            
            #line 83 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varName));
            
            #line default
            #line hidden
            this.Write(".HasValue)\r\n            {\r\n                ");
            
            #line 85 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varName));
            
            #line default
            #line hidden
            this.Write(" = Request.IsAuthenticated && \r\n                                    await UserMan" +
                    "ager.IsInRoleAsync(UserID, SecurityRoles.");
            
            #line 86 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(role.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            }\r\n            return ");
            
            #line 88 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varName));
            
            #line default
            #line hidden
            this.Write(".Value;\r\n        }\r\n        bool? ");
            
            #line 90 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 91 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\r\n        #region Find Methods for Entities\r\n");
            
            #line 94 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
  foreach (var entity in CodeEngine.Entities.Where(e => !e.EntityDefinition.Abstract))
    {
		var pkeyProperty = entity.GetPrimeryKey();
		string pKey = pkeyProperty == null ? "Id" : pkeyProperty.Name;

            
            #line default
            #line hidden
            this.Write("\r\n        protected virtual async Task<");
            
            #line 100 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("> FindAsync");
            
            #line 100 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("(int id)\r\n        {\r\n            return await ");
            
            #line 102 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write("\r\n                            .Get");
            
            #line 103 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("Query()\r\n                            .FirstOrDefaultAsync(x => x.");
            
            #line 104 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pKey));
            
            #line default
            #line hidden
            this.Write(" == id);\r\n        }\r\n");
            
            #line 106 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("        #endregion\r\n");
            
            #line 108 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
  if (CodeEngine.GenerateDataContext)
    { 
            
            #line default
            #line hidden
            this.Write(@"        
        protected void AppendExceptionMsg(Exception ex, StringBuilder sb)
        {
            if (ex == null)
                return;
            if (HttpContext.IsDebuggingEnabled)
            {
                sb.Append(ex.Message);
                sb.Append(""<br/>"");
                AppendExceptionMsg(ex.InnerException, sb);
            }
        }

        protected virtual ActionResult GetErrorResult(StringBuilder sb, HttpStatusCode statusCode)
        {
            Response.StatusCode = (int)statusCode;
            if (HttpContext.IsDebuggingEnabled)
            {
                sb.Append(""<br/><b>RouteData.Values</b><br/>"");
                foreach (var item in RouteData.Values)
                {
                    sb.Append(item.Key);
                    sb.Append("" : "");
                    sb.Append(item.Value);
                    sb.Append(""<br/>"");
                }
            }
            Response.StatusCode = (int)statusCode;
            return new ContentResult
            {
                ContentType = ""text/plain"",
                Content = sb.ToString(),
                ContentEncoding = Encoding.UTF8
            };
        }
        
        protected ");
            
            #line 146 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.DataContextClass));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 146 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get\r\n            {\r\n                if (_");
            
            #line 150 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n                {\r\n                    _");
            
            #line 152 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 152 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.DataContextClass));
            
            #line default
            #line hidden
            this.Write("();\r\n                }\r\n                return _");
            
            #line 154 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n        }\r\n        private ");
            
            #line 157 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.DataContextClass));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 157 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n        protected override void Dispose(bool disposing)\r\n        {\r\n        " +
                    "    if (disposing)\r\n            {\r\n                if (_");
            
            #line 163 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n                {\r\n                    _");
            
            #line 165 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".Dispose();\r\n                    _");
            
            #line 166 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n                }\r\n            }\r\n            base.Dispose(disposing);\r" +
                    "\n        }\r\n");
            
            #line 171 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcBaseController.tt"
   } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
