// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.AspNetMvc.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using OzzCodeGen.Templates;
    using OzzCodeGen.Templates.Cs;
    using OzzCodeGen.Definitions;
    using OzzUtils;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class MvcController : AbstractMvcController
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 10 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"

string dataContextIntance = CodeEngine.DataContextInstance;
var searchProperties = Entity.DisplayColumns.Where(e => e.UseInSearch);
var pkeyProperty = Entity.GetPrimeryKey();
string pKey = pkeyProperty == null ? "Id" : pkeyProperty.Name;

var strongForeignEntity = Entity.StrongForeignEntity;
var strongProperty = Entity.StrongForeignKeyProperty;
var foreignDependentProperty = Entity.GetForeignDependentProperty(strongProperty);
string[] createRoles = Entity.RolesCanCreateToArray();
string[] editRoles = Entity.RolesCanEditToArray();
string[] deleteRoles = Entity.RolesCanDeleteToArray();

WriteUsingNamespaces(); 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 25 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.ControllersNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial class ");
            
            #line 27 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("Controller");
            
            #line 27 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if (!CustomFile){ 
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 27 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.BaseControllerName));
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n    {\r\n");
            
            #line 29 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"

if (CustomFile)
{ 
    var vbagProperties = Entity.DisplayColumns.Where(e => (e.InCreateView | e.InEditView) & e.IsForeignKey());
    if (vbagProperties.Any())
    { 
            
            #line default
            #line hidden
            this.Write("        partial void SetViewBags(");
            
            #line 35 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 35 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 37 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
      foreach (var item in vbagProperties)
        { 
             WriteViewBagSelectList(item); 
         } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n");
            
            #line 43 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\r\n        //public new class QueryParameters : BaseController.QueryParameters\r\n  " +
                    "      //{\r\n\r\n        //}\r\n\r\n        //Purpose: To set default property values fo" +
                    "r newly created ");
            
            #line 50 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write(" entity\r\n        //partial void SetDefaults(");
            
            #line 51 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 51 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(") { }\r\n");
            
            #line 52 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 }
else 
{ 
            
            #line default
            #line hidden
            this.Write("        partial void SetViewBags(");
            
            #line 55 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 55 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        partial void SetDefaults(");
            
            #line 56 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 56 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        \r\n        ");
            
            #line 58 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanViewAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n        public async Task<ActionResult> Index(QueryParameters qParams)\r\n       " +
                    " {\r\n            var query = ");
            
            #line 61 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".Get");
            
            #line 61 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Query();\r\n");
            
            #line 62 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if(searchProperties.Any())
    { 
    int k = 0;
            
            #line default
            #line hidden
            this.Write("            if (!string.IsNullOrEmpty(qParams.SearchString))\r\n            {\r\n    " +
                    "            query = from a in query\r\n                        where\r\n");
            
            #line 69 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
        foreach (var item in searchProperties)
          {
            k++;
            
            #line default
            #line hidden
            this.Write("                            a.");
            
            #line 72 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(".Contains(qParams.SearchString)");
            
            #line 72 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if (k < searchProperties.Count()){ 
            
            #line default
            #line hidden
            this.Write(" |");
            
            #line 72 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 73 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
        } 
            
            #line default
            #line hidden
            this.Write("                        select a;\r\n            }\r\n");
            
            #line 76 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write(@"            qParams.TotalCount = await query.CountAsync();
            SetPagerParameters(qParams);

            ViewBag.canUserEdit = await CanUserEdit();
            ViewBag.canUserCreate = await CanUserCreate();
            ViewBag.canUserDelete = await CanUserDelete();

            if (qParams.TotalCount > 0)
            {
                return View(await query.Skip(qParams.Skip).Take(qParams.PageSize).ToListAsync());
            }
            else
            {
                return View(new List<");
            
            #line 90 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(">());   //there isn\'t any record, so no need to run a query\r\n            }\r\n     " +
                    "   }\r\n\r\n        ");
            
            #line 94 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanViewAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n        public async Task<ActionResult> Details(int? id)  //GET: /");
            
            #line 95 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Details/5\r\n        {\r\n            if (id == null)\r\n            {\r\n              " +
                    "  return new HttpStatusCodeResult(HttpStatusCode.BadRequest);\r\n            }\r\n  " +
                    "          ");
            
            #line 101 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 101 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = await FindAsync");
            
            #line 101 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("(id.Value);\r\n\r\n            if (");
            
            #line 103 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                return HttpNotFound();\r\n            }\r\n" +
                    "\r\n            return View(");
            
            #line 108 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        [HttpGet]\r\n        ");
            
            #line 112 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanEditAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 113 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if (strongForeignEntity != null)
    {    //TODO: Improve Route attirbute logic for fkey string types
 
            
            #line default
            #line hidden
            this.Write("        [Route(\"");
            
            #line 116 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Create/{");
            
            #line 116 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":");
            
            #line 116 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.GetNullableTypeName()));
            
            #line default
            #line hidden
            this.Write("}\")]\r\n        public async Task<ActionResult> Create(");
            
            #line 117 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.GetNullableTypeName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 117 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")  //GET: /");
            
            #line 117 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Create\r\n");
            
            #line 118 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("        public ActionResult Create()  //GET: /");
            
            #line 119 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Create\r\n");
            
            #line 120 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("        {\r\n            var ");
            
            #line 122 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 122 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 123 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if (strongForeignEntity != null)
    { 
        bool isString = strongProperty.IsString;
            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 126 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if(isString) { 
            
            #line default
            #line hidden
            this.Write("!string.IsNullOrEmpty(");
            
            #line 126 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            
            #line 126 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 126 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if(isString) { 
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 126 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write(" != null");
            
            #line 126 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            this.Write(")\r\n            {\r\n                var ");
            
            #line 128 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignDependentProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = await FindAsync");
            
            #line 128 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongForeignEntity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 128 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 128 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if(strongProperty.IsSimple) { 
            
            #line default
            #line hidden
            this.Write(".Value");
            
            #line 128 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            this.Write(");\r\n                if (");
            
            #line 129 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignDependentProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n                    return HttpNotFound();\r\n                ");
            
            #line 131 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 131 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignDependentProperty));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 131 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignDependentProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n");
            
            #line 133 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("            SetDefaults(");
            
            #line 134 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            SetViewBags(null);\r\n            return View(");
            
            #line 136 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        [HttpPost]\r\n        ");
            
            #line 140 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanEditAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n        [ValidateAntiForgeryToken]\r\n");
            
            #line 142 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if (strongForeignEntity != null)
    {    //TODO: Improve Route attirbute logic for fkey string types
 
            
            #line default
            #line hidden
            this.Write("        [Route(\"");
            
            #line 145 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Create/{");
            
            #line 145 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":");
            
            #line 145 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.GetNullableTypeName()));
            
            #line default
            #line hidden
            this.Write("}\")]\r\n        public async Task<ActionResult> Create(");
            
            #line 146 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.GetNullableTypeName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 146 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 146 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 146 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")  //POST: /");
            
            #line 146 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Create\r\n");
            
            #line 147 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("        public async Task<ActionResult> Create(");
            
            #line 148 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 148 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")  //POST: /");
            
            #line 148 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Create\r\n");
            
            #line 149 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("        {\r\n            ");
            
            #line 151 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".SetInsertDefaults(");
            
            #line 151 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", this);\r\n\r\n            if (ModelState.IsValid)\r\n            {\r\n");
            
            #line 155 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if(Entity.ModelForEdit == Entity.Name) {
            
            #line default
            #line hidden
            this.Write(" \r\n                ");
            
            #line 156 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 156 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.DataSetName));
            
            #line default
            #line hidden
            this.Write(".Add(");
            
            #line 156 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 157 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 158 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 158 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.DataSetName));
            
            #line default
            #line hidden
            this.Write(".Add(");
            
            #line 158 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".To");
            
            #line 158 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("());\r\n");
            
            #line 159 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("                await ");
            
            #line 160 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".SaveChangesAsync(");
            
            #line 160 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.SaveParameter));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 161 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if (Entity.CreateToDetails) {  
            
            #line default
            #line hidden
            this.Write("                return RedirectToAction(\"Details\", new { Id = ");
            
            #line 162 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 162 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pKey));
            
            #line default
            #line hidden
            this.Write(" });\r\n");
            
            #line 163 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                return RedirectToAction(\"Index\");\r\n");
            
            #line 165 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("            }\r\n\r\n            SetViewBags(");
            
            #line 168 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            return View(");
            
            #line 169 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n        \r\n        protected virtual async Task<bool> CanUserCreate" +
                    "()\r\n        {\r\n            if (!_canUserCreate.HasValue)\r\n            {\r\n       " +
                    "         _canUserCreate = ");
            
            #line 176 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.MergeIsUserMethods(createRoles)));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n            return _canUserCreate.Value;\r\n        }\r\n        bo" +
                    "ol? _canUserCreate;\r\n\r\n        ");
            
            #line 182 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanEditAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n        public async Task<ActionResult> Edit(int? id)  //GET: /");
            
            #line 183 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Edit/5\r\n        {\r\n            if (id == null)\r\n            {\r\n                r" +
                    "eturn new HttpStatusCodeResult(HttpStatusCode.BadRequest);\r\n            }\r\n     " +
                    "       ");
            
            #line 189 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 189 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = await FindAsync");
            
            #line 189 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("(id.Value);\r\n\r\n            if (");
            
            #line 191 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                return HttpNotFound();\r\n            }\r\n" +
                    "\r\n");
            
            #line 196 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  string instanceName = Entity.ModelForEdit == Entity.Name ? Entity.Name.ToCamelCase() : Entity.ModelForEdit.ToCamelCase();
    if(Entity.ModelForEdit != Entity.Name)
    { 
            
            #line default
            #line hidden
            this.Write("            var ");
            
            #line 199 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instanceName));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 199 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 199 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 200 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("            SetViewBags(");
            
            #line 201 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instanceName));
            
            #line default
            #line hidden
            this.Write(");\r\n            return View(");
            
            #line 202 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instanceName));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        ");
            
            #line 205 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanEditAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n        [HttpPost]\r\n        [ValidateAntiForgeryToken]\r\n        public async Ta" +
                    "sk<ActionResult> Edit(");
            
            #line 208 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 208 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")  //POST: /");
            
            #line 208 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Edit/5\r\n        {\r\n            ");
            
            #line 210 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".SetInsertDefaults(");
            
            #line 210 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", this);\r\n\r\n            if (ModelState.IsValid)\r\n            {\r\n");
            
            #line 214 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if(Entity.ModelForEdit == Entity.Name)
    {
            
            #line default
            #line hidden
            this.Write(" \r\n                ");
            
            #line 216 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".Entry(");
            
            #line 216 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(").State = EntityState.Modified;\r\n");
            
            #line 217 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 218 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".Entry(");
            
            #line 218 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".To");
            
            #line 218 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("()).State = EntityState.Modified;\r\n");
            
            #line 219 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("                await ");
            
            #line 220 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".SaveChangesAsync(");
            
            #line 220 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.SaveParameter));
            
            #line default
            #line hidden
            this.Write(");\r\n                return RedirectToAction(\"Index\");\r\n            }\r\n\r\n         " +
                    "   SetViewBags(");
            
            #line 224 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            return View(");
            
            #line 225 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        protected virtual async Task<bool> CanUserEdit()\r\n      " +
                    "  {\r\n            if (!_canUserEdit.HasValue)\r\n            {\r\n                _ca" +
                    "nUserEdit = ");
            
            #line 232 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.MergeIsUserMethods(editRoles)));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n            return _canUserEdit.Value;\r\n        }\r\n        bool" +
                    "? _canUserEdit;\r\n\r\n        ");
            
            #line 238 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanDeleteAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n        public async Task<ActionResult> Delete(int? id)  //GET: /");
            
            #line 239 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Delete/5\r\n        {\r\n            if (id == null)\r\n            {\r\n               " +
                    " return new HttpStatusCodeResult(HttpStatusCode.BadRequest);\r\n            }\r\n   " +
                    "         ");
            
            #line 245 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 245 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = await FindAsync");
            
            #line 245 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("(id.Value);\r\n\r\n            if (");
            
            #line 247 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                return HttpNotFound();\r\n            }\r\n" +
                    "            \r\n            ");
            
            #line 252 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 252 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.DataSetName));
            
            #line default
            #line hidden
            this.Write(".Remove(");
            
            #line 252 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            await ");
            
            #line 253 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".SaveChangesAsync(");
            
            #line 253 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.SaveParameter));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n            return RedirectToAction(\"Index\");\r\n        }\r\n        \r\n       " +
                    " protected virtual async Task<bool> CanUserDelete()\r\n        {\r\n            if (" +
                    "!_canUserDelete.HasValue)\r\n            {\r\n                _canUserDelete = ");
            
            #line 262 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.MergeIsUserMethods(deleteRoles)));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n            return _canUserDelete.Value;\r\n        }\r\n        bo" +
                    "ol? _canUserDelete;\r\n");
            
            #line 267 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 270 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 
protected void WriteViewBagSelectList(AspNetMvcPropertySetting propertySetting)
{
    var codeEngine = Entity.CodeEngine;
    string dataContextIntance = CodeEngine.DataContextInstance;
    var foreign = CodeEngine.GetForeignKeyEntity(propertySetting);
    string propValue = propertySetting.IsNullable() ? "(" : "";
    propValue += Entity.Name.ToCamelCase();
    propValue += ".";
    propValue += propertySetting.Name;
    if(propertySetting.IsNullable())
    {
        propValue += " ?? 0)";
    }
    if (foreign == null)
    { 
        
        #line default
        #line hidden
        
        #line 285 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("            //Can\'t detect forein entity type for ");

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name));

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("\r\n            //TODO: ViewBag.");

        
        #line default
        #line hidden
        
        #line 287 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name));

        
        #line default
        #line hidden
        
        #line 287 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(" = new SelectList(");

        
        #line default
        #line hidden
        
        #line 287 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));

        
        #line default
        #line hidden
        
        #line 287 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(".QueryName, \"Id\", \"Title\", 0);\r\n");

        
        #line default
        #line hidden
        
        #line 288 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
    }
    else
    {
        string comment = propertySetting.UseForEdit != "DropDownList" ? "//" : string.Empty;
        var pkey = foreign.GetPrimeryKey();
        string pkeyName = pkey == null ? "Id" : pkey.Name;
                 
        
        #line default
        #line hidden
        
        #line 294 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("            //TODO: Optimize query\r\n            var query");

        
        #line default
        #line hidden
        
        #line 296 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name));

        
        #line default
        #line hidden
        
        #line 296 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(" = ");

        
        #line default
        #line hidden
        
        #line 296 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));

        
        #line default
        #line hidden
        
        #line 296 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 296 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(foreign.GetDataSetQuery()));

        
        #line default
        #line hidden
        
        #line 296 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(";\r\n            ");

        
        #line default
        #line hidden
        
        #line 297 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(comment));

        
        #line default
        #line hidden
        
        #line 297 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("int ");

        
        #line default
        #line hidden
        
        #line 297 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name.ToCamelCase()));

        
        #line default
        #line hidden
        
        #line 297 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(" = ");

        
        #line default
        #line hidden
        
        #line 297 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));

        
        #line default
        #line hidden
        
        #line 297 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(" == null ? 0 : ");

        
        #line default
        #line hidden
        
        #line 297 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propValue));

        
        #line default
        #line hidden
        
        #line 297 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(";\r\n            ");

        
        #line default
        #line hidden
        
        #line 298 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(comment));

        
        #line default
        #line hidden
        
        #line 298 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("ViewBag.");

        
        #line default
        #line hidden
        
        #line 298 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name));

        
        #line default
        #line hidden
        
        #line 298 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(" = new SelectList(query");

        
        #line default
        #line hidden
        
        #line 298 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name));

        
        #line default
        #line hidden
        
        #line 298 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(", \"");

        
        #line default
        #line hidden
        
        #line 298 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkeyName));

        
        #line default
        #line hidden
        
        #line 298 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("\", \"");

        
        #line default
        #line hidden
        
        #line 298 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(foreign.EntityDefinition.DisplayMember));

        
        #line default
        #line hidden
        
        #line 298 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("\", ");

        
        #line default
        #line hidden
        
        #line 298 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name.ToCamelCase()));

        
        #line default
        #line hidden
        
        #line 298 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 299 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            }
} 
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
