// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.AspNetMvc.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using OzzCodeGen.Templates;
    using OzzCodeGen.Templates.Cs;
    using OzzCodeGen.Definitions;
    using OzzUtils;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class MvcController : AbstractMvcController
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 10 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"

string dataContextIntance = CodeEngine.DataContextInstance;
var searchProperties = Entity.DisplayColumns.Where(e => e.UseInSearch);
var collectionProperties = Entity.GetInheritedCollectionProperties();

var pkeyProperty = Entity.GetPrimeryKey();
string pKey = pkeyProperty == null ? "Id" : pkeyProperty.Name;

var fkeyProperties = Entity.DisplayColumns.Where(e => (e.InCreateView | e.InEditView) & e.IsForeignKey());

var strongForeignEntity = Entity.StrongForeignEntity;
var strongProperty = Entity.StrongForeignKeyProperty;
var foreignDependentProperty = Entity.GetForeignDependentProperty(strongProperty);
string[] createRoles = Entity.RolesCanCreateToArray();
string[] editRoles = Entity.RolesCanEditToArray();
string[] deleteRoles = Entity.RolesCanDeleteToArray();

WriteUsingNamespaces(); 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 29 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.ControllersNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial class ");
            
            #line 31 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("Controller");
            
            #line 31 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if (!CustomFile){ 
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 31 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.BaseControllerName));
            
            #line default
            #line hidden
            
            #line 31 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n    {\r\n");
            
            #line 33 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"

if (CustomFile)
{ 
    if (fkeyProperties.Any())
    { 
            
            #line default
            #line hidden
            this.Write("        partial void SetViewBags(");
            
            #line 38 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 38 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 40 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
      foreach (var item in fkeyProperties)
        { 
             WriteViewBagSelectList(item); 
         } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n");
            
            #line 46 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\r\n        //Purpose: To set default property values for newly created ");
            
            #line 48 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" entity\r\n        //partial void SetDefaults(");
            
            #line 49 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 49 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(") { }\r\n");
            
            #line 50 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 }
else 
{ 
            
            #line default
            #line hidden
            
            #line 53 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if (Entity.GenerateIndexAction){ 
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 54 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanViewAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n        public async Task<ActionResult> Index(QueryParameters qParams)\r\n       " +
                    " {\r\n            var query = ");
            
            #line 57 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".Get");
            
            #line 57 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("Query();\r\n");
            
            #line 58 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if(searchProperties.Any())
    { 
    int k = 0;
            
            #line default
            #line hidden
            this.Write("            if (!string.IsNullOrEmpty(qParams.SearchString))\r\n            {\r\n    " +
                    "            query = from a in query\r\n                        where\r\n");
            
            #line 65 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
        foreach (var item in searchProperties)
          {
            k++;
            
            #line default
            #line hidden
            this.Write("                            a.");
            
            #line 68 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(".Contains(qParams.SearchString)");
            
            #line 68 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if (k < searchProperties.Count()){ 
            
            #line default
            #line hidden
            this.Write(" |");
            
            #line 68 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 69 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
        } 
            
            #line default
            #line hidden
            this.Write("                        select a;\r\n            }\r\n");
            
            #line 72 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            
            #line 73 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  foreach (var item in fkeyProperties)
    {  
            
            #line default
            #line hidden
            this.Write("            if (qParams.");
            
            #line 75 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n            {\r\n                query = query.Where(x => x.");
            
            #line 77 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" == qParams.");
            
            #line 77 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n            }\r\n");
            
            #line 79 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write(@"            qParams.TotalCount = await query.CountAsync();
            SetPagerParameters(qParams);

            ViewBag.canUserEdit = await CanUserEdit();
            ViewBag.canUserCreate = await CanUserCreate();
            ViewBag.canUserDelete = await CanUserDelete();

            if (qParams.TotalCount > 0)
            {
                return View(await query.Skip(qParams.Skip).Take(qParams.PageSize).ToListAsync());
            }
            else
            {
                return View(new List<");
            
            #line 93 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(@">());   //there isn't any record, so no need to run a query
            }
        }
        
        protected virtual async Task<bool> CanUserCreate()
        {
            if (!_canUserCreate.HasValue)
            {
                _canUserCreate = ");
            
            #line 101 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.MergeIsUserMethods(createRoles)));
            
            #line default
            #line hidden
            this.Write(@";
            }
            return _canUserCreate.Value;
        }
        bool? _canUserCreate;

        protected virtual async Task<bool> CanUserEdit()
        {
            if (!_canUserEdit.HasValue)
            {
                _canUserEdit = ");
            
            #line 111 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.MergeIsUserMethods(editRoles)));
            
            #line default
            #line hidden
            this.Write(@";
            }
            return _canUserEdit.Value;
        }
        bool? _canUserEdit;
        
        protected virtual async Task<bool> CanUserDelete()
        {
            if (!_canUserDelete.HasValue)
            {
                _canUserDelete = ");
            
            #line 121 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.MergeIsUserMethods(deleteRoles)));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n            return _canUserDelete.Value;\r\n        }\r\n        bo" +
                    "ol? _canUserDelete;\r\n");
            
            #line 126 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            
            #line 127 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if (Entity.GenerateDetailsAction){ 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n        ");
            
            #line 130 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanViewAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n        public async Task<ActionResult> Details(int? id)  //GET: /");
            
            #line 131 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Details/5\r\n        {\r\n            if (id == null)\r\n            {\r\n              " +
                    "  return new HttpStatusCodeResult(HttpStatusCode.BadRequest);\r\n            }\r\n  " +
                    "          ");
            
            #line 137 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 137 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = await FindAsync");
            
            #line 137 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("(id.Value);\r\n\r\n            if (");
            
            #line 139 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                return HttpNotFound();\r\n            }\r\n" +
                    "\r\n            return View(");
            
            #line 144 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n");
            
            #line 146 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            
            #line 147 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if (Entity.GenerateCreateAction){ 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n        [HttpGet]\r\n        ");
            
            #line 151 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanEditAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 152 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if (strongForeignEntity != null)
    {    //TODO: Improve Route attirbute logic for fkey string types
 
            
            #line default
            #line hidden
            this.Write("        [Route(\"");
            
            #line 155 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Create/{");
            
            #line 155 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":");
            
            #line 155 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.GetNullableTypeName()));
            
            #line default
            #line hidden
            this.Write("}\")]\r\n        public async Task<ActionResult> Create(");
            
            #line 156 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.GetNullableTypeName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 156 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")  //GET: /");
            
            #line 156 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Create\r\n");
            
            #line 157 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("        public ActionResult Create()  //GET: /");
            
            #line 158 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Create\r\n");
            
            #line 159 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("        {\r\n            var ");
            
            #line 161 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 161 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForCreate));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 162 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if (strongForeignEntity != null)
    { 
        bool isString = strongProperty.IsString;
            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 165 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if(isString) { 
            
            #line default
            #line hidden
            this.Write("!string.IsNullOrEmpty(");
            
            #line 165 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            
            #line 165 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 165 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if(isString) { 
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 165 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write(" != null");
            
            #line 165 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            this.Write(")\r\n            {\r\n                var ");
            
            #line 167 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignDependentProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = await FindAsync");
            
            #line 167 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongForeignEntity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 167 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 167 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if(strongProperty.IsSimple) { 
            
            #line default
            #line hidden
            this.Write(".Value");
            
            #line 167 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            this.Write(");\r\n                if (");
            
            #line 168 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignDependentProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n                    return HttpNotFound();\r\n                ");
            
            #line 170 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 170 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignDependentProperty));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 170 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignDependentProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n");
            
            #line 172 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("            SetDefaults(");
            
            #line 173 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            SetViewBags(null);\r\n            return View(");
            
            #line 175 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        [HttpPost]\r\n        ");
            
            #line 179 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanEditAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n        [ValidateAntiForgeryToken]\r\n");
            
            #line 181 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if (strongForeignEntity != null)
    {    //TODO: Improve Route attirbute logic for fkey string types
 
            
            #line default
            #line hidden
            this.Write("        [Route(\"");
            
            #line 184 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Create/{");
            
            #line 184 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(":");
            
            #line 184 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.GetNullableTypeName()));
            
            #line default
            #line hidden
            this.Write("}\")]\r\n        public async Task<ActionResult> Create(");
            
            #line 185 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.GetNullableTypeName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 185 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strongProperty.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 185 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForCreate));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 185 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")  //POST: /");
            
            #line 185 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Create\r\n");
            
            #line 186 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("        public async Task<ActionResult> Create(");
            
            #line 187 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForCreate));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 187 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")  //POST: /");
            
            #line 187 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Create\r\n");
            
            #line 188 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("        {\r\n            ");
            
            #line 190 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".SetInsertDefaults(");
            
            #line 190 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", this);\r\n\r\n            if (ModelState.IsValid)\r\n            {\r\n                O" +
                    "nCreateSaving(");
            
            #line 194 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 195 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if(Entity.ModelForCreate == Entity.Name) {
            
            #line default
            #line hidden
            this.Write(" \r\n                ");
            
            #line 196 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 196 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.DataSetName));
            
            #line default
            #line hidden
            this.Write(".Add(");
            
            #line 196 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 197 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                var entity = ");
            
            #line 198 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".To");
            
            #line 198 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n                ");
            
            #line 199 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 199 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.DataSetName));
            
            #line default
            #line hidden
            this.Write(".Add(entity);\r\n");
            
            #line 200 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("                await ");
            
            #line 201 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".SaveChangesAsync(");
            
            #line 201 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.SaveParameter));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 202 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if(Entity.ModelForCreate == Entity.Name) {
            
            #line default
            #line hidden
            this.Write(" \r\n                OnCreateSaved(");
            
            #line 203 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 204 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                OnCreateSaved(entity);\r\n");
            
            #line 206 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("                return RedirectToAction(");
            
            #line 207 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.AfterSaveRedirect));
            
            #line default
            #line hidden
            this.Write(");\r\n            }\r\n\r\n            SetViewBags(");
            
            #line 210 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            return View(");
            
            #line 211 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n");
            
            #line 213 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            
            #line 214 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if (Entity.GenerateEditAction){ 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n        ");
            
            #line 217 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanEditAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n        public async Task<ActionResult> Edit(int? id)  //GET: /");
            
            #line 218 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Edit/5\r\n        {\r\n            if (id == null)\r\n            {\r\n                r" +
                    "eturn new HttpStatusCodeResult(HttpStatusCode.BadRequest);\r\n            }\r\n     " +
                    "       ");
            
            #line 224 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 224 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = await FindAsync");
            
            #line 224 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("(id.Value);\r\n\r\n            if (");
            
            #line 226 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                return HttpNotFound();\r\n            }\r\n" +
                    "\r\n");
            
            #line 231 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  string instanceName = Entity.ModelForEdit == Entity.Name ? Entity.Name.ToCamelCase() : Entity.ModelForEdit.ToCamelCase();
    if(Entity.ModelForEdit != Entity.Name)
    { 
            
            #line default
            #line hidden
            this.Write("            var ");
            
            #line 234 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instanceName));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 234 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 234 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 235 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("            SetViewBags(");
            
            #line 236 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instanceName));
            
            #line default
            #line hidden
            this.Write(");\r\n            return View(");
            
            #line 237 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(instanceName));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        ");
            
            #line 240 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanEditAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n        [HttpPost]\r\n        [ValidateAntiForgeryToken]\r\n        public async Ta" +
                    "sk<ActionResult> Edit(");
            
            #line 243 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 243 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")  //POST: /");
            
            #line 243 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Edit/5\r\n        {\r\n            ");
            
            #line 245 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".SetInsertDefaults(");
            
            #line 245 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", this);\r\n\r\n            if (ModelState.IsValid)\r\n            {\r\n                O" +
                    "nEditSaving(");
            
            #line 249 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 250 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if(Entity.ModelForEdit == Entity.Name)
    {
            
            #line default
            #line hidden
            this.Write(" \r\n                ");
            
            #line 252 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".Entry(");
            
            #line 252 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(").State = EntityState.Modified;\r\n");
            
            #line 253 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                var entity = ");
            
            #line 254 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".To");
            
            #line 254 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n                ");
            
            #line 255 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".Entry(entity).State = EntityState.Modified;\r\n");
            
            #line 256 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("                await ");
            
            #line 257 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".SaveChangesAsync(");
            
            #line 257 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.SaveParameter));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 258 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if(Entity.ModelForEdit == Entity.Name) {
            
            #line default
            #line hidden
            this.Write(" \r\n                OnEditSaved(");
            
            #line 259 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 260 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                OnEditSaved(entity);\r\n");
            
            #line 262 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("                return RedirectToAction(");
            
            #line 263 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.AfterSaveRedirect));
            
            #line default
            #line hidden
            this.Write(");\r\n            }\r\n\r\n            SetViewBags(");
            
            #line 266 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            return View(");
            
            #line 267 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n");
            
            #line 269 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            
            #line 270 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if (Entity.GenerateDeleteAction){ 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n        ");
            
            #line 273 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CanDeleteAttrib));
            
            #line default
            #line hidden
            this.Write("\r\n        public async Task<ActionResult> Delete(int? id)  //GET: /");
            
            #line 274 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("/Delete/5\r\n        {\r\n            if (id == null)\r\n            {\r\n               " +
                    " return new HttpStatusCodeResult(HttpStatusCode.BadRequest);\r\n            }\r\n   " +
                    "         ");
            
            #line 280 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 280 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = await FindAsync");
            
            #line 280 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("(id.Value);\r\n\r\n            if (");
            
            #line 282 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                return HttpNotFound();\r\n            }\r\n" +
                    "\r\n");
            
            #line 287 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  if (collectionProperties.Any()) 
    { 
            
            #line default
            #line hidden
            
            #line 289 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
      foreach (var property in collectionProperties) 
        { 
            
            #line default
            #line hidden
            this.Write("            int ");
            
            #line 291 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Count = ");
            
            #line 291 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 291 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(".Count;\r\n");
            
            #line 292 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
      } 
            
            #line default
            #line hidden
            this.Write("            if ((");
            
            #line 293 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 int i = 0; foreach (var property in collectionProperties){ 
            
            #line default
            #line hidden
            
            #line 293 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 if(i>0){ 
            
            #line default
            #line hidden
            this.Write(" + ");
            
            #line 293 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } i++; 
            
            #line default
            #line hidden
            
            #line 293 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Count");
            
            #line 293 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            this.Write(") > 0)\r\n            {\r\n                var sb = new StringBuilder();\r\n\r\n         " +
                    "       sb.Append(MessageStrings.CanNotDelete);\r\n                sb.Append(\" <b>\"" +
                    ");\r\n                sb.Append(");
            
            #line 299 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 299 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.EntityDefinition.DisplayMember));
            
            #line default
            #line hidden
            this.Write(");\r\n                sb.Append(\"</b>.<br/>\");\r\n                sb.Append(MessageSt" +
                    "rings.BecauseOfRelatedRecords);\r\n                sb.Append(\".<br/>\");\r\n\r\n");
            
            #line 304 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
      foreach (var property in collectionProperties) 
        { 
            
            #line default
            #line hidden
            this.Write("                if (");
            
            #line 306 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Count > 0)\r\n                {\r\n                    sb.Append(");
            
            #line 308 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 308 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n                    sb.Append(\": \");\r\n                    sb.Append(");
            
            #line 310 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Count);\r\n                    sb.Append(\"<br/>\");\r\n                }\r\n\r\n");
            
            #line 314 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
      } 
            
            #line default
            #line hidden
            this.Write("                return GetErrorResult(sb, HttpStatusCode.BadRequest);\r\n          " +
                    "  }\r\n\r\n");
            
            #line 318 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 319 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 319 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.DataSetName));
            
            #line default
            #line hidden
            this.Write(".Remove(");
            
            #line 319 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            try\r\n            {\r\n                await ");
            
            #line 322 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));
            
            #line default
            #line hidden
            this.Write(".SaveChangesAsync(");
            
            #line 322 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.SaveParameter));
            
            #line default
            #line hidden
            this.Write(");\r\n            }\r\n            catch (Exception ex)\r\n            {\r\n             " +
                    "   var sb = new StringBuilder();\r\n                sb.Append(MessageStrings.CanNo" +
                    "tDelete);\r\n                sb.Append(");
            
            #line 328 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 328 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.EntityDefinition.DisplayMember));
            
            #line default
            #line hidden
            this.Write(@");
                sb.Append(""<br/>"");
                AppendExceptionMsg(ex, sb);

                return GetErrorResult(sb, HttpStatusCode.InternalServerError);
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
");
            
            #line 337 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 339 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
    if (fkeyProperties.Any())
    { 
            
            #line default
            #line hidden
            this.Write("        public new partial class QueryParameters : ");
            
            #line 341 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeEngine.BaseControllerName));
            
            #line default
            #line hidden
            this.Write(".QueryParameters\r\n        {\r\n");
            
            #line 343 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
      foreach (var item in fkeyProperties)
        {  
            
            #line default
            #line hidden
            this.Write("            public ");
            
            #line 345 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.GetNullableTypeName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 345 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 346 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
       } 
            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 348 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\r\n        //Partial methods\r\n        partial void OnCreateSaving(");
            
            #line 351 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForCreate));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 351 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        partial void OnCreateSaved(");
            
            #line 352 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 352 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        partial void OnEditSaving(");
            
            #line 353 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForEdit));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 353 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        partial void OnEditSaved(");
            
            #line 354 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 354 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        partial void SetDefaults(");
            
            #line 355 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ModelForCreate));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 355 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        partial void SetViewBags(");
            
            #line 356 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 356 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 357 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 360 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
 
protected void WriteViewBagSelectList(AspNetMvcPropertySetting propertySetting)
{
    var codeEngine = Entity.CodeEngine;
    string dataContextIntance = CodeEngine.DataContextInstance;
    var foreign = CodeEngine.GetForeignKeyEntity(propertySetting);
    string propValue = propertySetting.IsNullable() ? "(" : "";
    propValue += Entity.Name.ToCamelCase();
    propValue += ".";
    propValue += propertySetting.Name;
    if(propertySetting.IsNullable())
    {
        propValue += " ?? 0)";
    }
    if (foreign == null)
    { 
        
        #line default
        #line hidden
        
        #line 375 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("            //Can\'t detect forein entity type for ");

        
        #line default
        #line hidden
        
        #line 376 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name));

        
        #line default
        #line hidden
        
        #line 376 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("\r\n            //TODO: ViewBag.");

        
        #line default
        #line hidden
        
        #line 377 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name));

        
        #line default
        #line hidden
        
        #line 377 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(" = new SelectList(");

        
        #line default
        #line hidden
        
        #line 377 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));

        
        #line default
        #line hidden
        
        #line 377 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(".QueryName, \"Id\", \"Title\", 0);\r\n");

        
        #line default
        #line hidden
        
        #line 378 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
    }
    else
    {
        string comment = propertySetting.UseForEdit != "DropDownList" ? "//" : string.Empty;
        var pkey = foreign.GetPrimeryKey();
        string pkeyName = pkey == null ? "Id" : pkey.Name;
                 
        
        #line default
        #line hidden
        
        #line 384 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("            //TODO: Optimize query\r\n            var query");

        
        #line default
        #line hidden
        
        #line 386 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name));

        
        #line default
        #line hidden
        
        #line 386 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(" = ");

        
        #line default
        #line hidden
        
        #line 386 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dataContextIntance));

        
        #line default
        #line hidden
        
        #line 386 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 386 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(foreign.GetDataSetQuery()));

        
        #line default
        #line hidden
        
        #line 386 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(";\r\n            ");

        
        #line default
        #line hidden
        
        #line 387 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(comment));

        
        #line default
        #line hidden
        
        #line 387 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("int ");

        
        #line default
        #line hidden
        
        #line 387 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name.ToCamelCase()));

        
        #line default
        #line hidden
        
        #line 387 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(" = ");

        
        #line default
        #line hidden
        
        #line 387 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.ToCamelCase()));

        
        #line default
        #line hidden
        
        #line 387 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(" == null ? 0 : ");

        
        #line default
        #line hidden
        
        #line 387 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propValue));

        
        #line default
        #line hidden
        
        #line 387 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(";\r\n            ");

        
        #line default
        #line hidden
        
        #line 388 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(comment));

        
        #line default
        #line hidden
        
        #line 388 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("ViewBag.");

        
        #line default
        #line hidden
        
        #line 388 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name));

        
        #line default
        #line hidden
        
        #line 388 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(" = new SelectList(query");

        
        #line default
        #line hidden
        
        #line 388 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name));

        
        #line default
        #line hidden
        
        #line 388 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(", \"");

        
        #line default
        #line hidden
        
        #line 388 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pkeyName));

        
        #line default
        #line hidden
        
        #line 388 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("\", \"");

        
        #line default
        #line hidden
        
        #line 388 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(foreign.EntityDefinition.DisplayMember));

        
        #line default
        #line hidden
        
        #line 388 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write("\", ");

        
        #line default
        #line hidden
        
        #line 388 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertySetting.Name.ToCamelCase()));

        
        #line default
        #line hidden
        
        #line 388 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 389 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcController.tt"
            }
} 
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
