// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.AspNetMvc.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using OzzCodeGen.Templates;
    using OzzCodeGen.Templates.Cs;
    using OzzCodeGen.Definitions;
    using OzzCodeGen.Utilities;
    using OzzUtils;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class MvcEditView : AbstractMvcView
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 11 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
 
var properties = CreateForm ? 
        Entity.DisplayColumns.Where(e => e.InCreateView) :
        Entity.DisplayColumns.Where(e => e.InEditView);

string modelName = CreateForm ? Entity.ModelForCreate : Entity.ModelForEdit;
WriteUsingNamespaces(); 
            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 18 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("\r\n@{\r\n");
            
            #line 20 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
  if(CreateForm)
    { 
            
            #line default
            #line hidden
            this.Write("    ViewBag.Title = ");
            
            #line 22 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".Create");
            
            #line 22 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 23 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("    ViewBag.Title = ");
            
            #line 24 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".Edit");
            
            #line 24 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 25 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
  } 
            
            #line default
            #line hidden
            this.Write(@"}
<h2 class=""col-lg-offset-2 col-md-offset-3 col-sm-offset-3"">@ViewBag.Title</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class=""form-horizontal"">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        
");
            
            #line 36 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"

foreach (var property in properties) 
{
	var useFor = CreateForm ? property.UseForCreate : property.UseForEdit;
    if (useFor == "HiddenInput")
    { 
            
            #line default
            #line hidden
            this.Write("        @Html.HiddenFor(m => m.");
            
            #line 42 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 43 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
  }
    else 
    {
        string editDivClass = useFor == "TextArea" ? "col-lg-7 col-md-8 col-sm-9" : "col-lg-5 col-md-6 col-sm-7"; 
            
            #line default
            #line hidden
            this.Write("        <div class=\"form-group\">\r\n            @Html.LabelFor(model => model.");
            
            #line 48 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(", htmlAttributes: new { @class = \"control-label col-lg-2 col-md-3 col-sm-3\" })\r\n " +
                    "           <div class=\"");
            
            #line 49 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(editDivClass));
            
            #line default
            #line hidden
            this.Write("\">\r\n");
            
            #line 50 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
      if (useFor == "DropDownList")
        { 
            
            #line default
            #line hidden
            this.Write("                @Html.DropDownListFor(m => m.");
            
            #line 52 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(", null, ActionStrings.SelectPlease, htmlAttributes: new { @class = \"form-control\"" +
                    " })\r\n");
            
            #line 53 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
      } else if (useFor == "ReadOnlyDisplay") { 
            
            #line default
            #line hidden
            this.Write("                @Html.EditorFor(m => m.");
            
            #line 54 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(", new { htmlAttributes = new { @class = \"form-control\", @readonly = \"readonly\" } " +
                    "})\r\n");
            
            #line 55 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
      } else if (useFor == "ImageUpload") { 
            
            #line default
            #line hidden
            this.Write("                @Html.Partial(\"_ImageUpload\", new ImageUploadViewModel(\"");
            
            #line 56 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\", Model.");
            
            #line 56 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("))\r\n");
            
            #line 57 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
      } else if (useFor == "TextBox") { 
            
            #line default
            #line hidden
            this.Write("                @Html.TextBoxFor(m => m.");
            
            #line 58 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(", new { @class = \"form-control\", autocomplete = \"off\" })\r\n");
            
            #line 59 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
      } else if (useFor == "TextArea") { 
            
            #line default
            #line hidden
            this.Write("                @Html.TextAreaFor(m => m.");
            
            #line 60 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(", 4, 1, new { @class = \"form-control\", autocomplete = \"off\" })\r\n");
            
            #line 61 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
      } else { 
            
            #line default
            #line hidden
            this.Write("                @Html.EditorFor(m => m.");
            
            #line 62 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(", new { htmlAttributes = new { @class = \"form-control\", autocomplete = \"off\" } })" +
                    "\r\n");
            
            #line 63 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
      } 
            
            #line default
            #line hidden
            
            #line 64 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
      if (property.HasValidation)
        { 
            
            #line default
            #line hidden
            this.Write("                @Html.ValidationMessageFor(m => m.");
            
            #line 66 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(", \"\", new { @class = \"text-danger\" })\r\n");
            
            #line 67 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
      } 
            
            #line default
            #line hidden
            this.Write("            </div>\r\n        </div>\r\n");
            
            #line 70 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
  } 
            
            #line default
            #line hidden
            
            #line 71 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"

} 
            
            #line default
            #line hidden
            this.Write("        @Html.Partial(\"");
            
            #line 73 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MvcPartialSaveButtons.ViewName));
            
            #line default
            #line hidden
            this.Write("\")\r\n    </div>\r\n}\r\n@section Scripts\r\n{\r\n    @Scripts.Render(\"~/bundles/jqueryval\"" +
                    ")\r\n");
            
            #line 79 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
  if(properties.Where(p => p.UseForCreate == "ImageUpload" || p.UseForEdit == "ImageUpload").Any())
    { 
            
            #line default
            #line hidden
            this.Write("    @Scripts.Render(\"~/bundles/angular\")\r\n    @Scripts.Render(\"~/bundles/fileUplo" +
                    "ad\")\r\n");
            
            #line 83 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
  } 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 85 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
  if(properties.Where(p => p.UseForCreate == "ImageUpload" || p.UseForEdit == "ImageUpload").Any())
    { 
            
            #line default
            #line hidden
            this.Write("@section styles{\r\n    <link href=\"~/Content/fileupload.css\" rel=\"stylesheet\" />\r\n" +
                    "}\r\n");
            
            #line 90 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcEditView.tt"
  } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
