// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.AspNetMvc.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using OzzCodeGen.Templates;
    using OzzCodeGen.Templates.Cs;
    using OzzCodeGen.Definitions;
    using OzzUtils;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class MvcIndexView : AbstracMvcIndexView
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 10 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
 
bool searchable = Entity.DisplayColumns.Where(e => e.UseInSearch).Any();
var properties = Entity.DisplayColumns.Where(e => e.InIndexView);
var collectionProperties = Entity.GetInheritedCollectionProperties();
var entitiesThisForCreate = Entity.GetEntitiesStrongForThis();
var gridId = Entity.Name.ToCamelCase() + "Grid";

var pkeyProperty = Entity.GetPrimaryKey();
string pKey = pkeyProperty == null ? "Id" : pkeyProperty.Name;

bool hasScript = (Entity.IndexViewGeneration == IndexViewGeneration.HtmlTableWithMenuAction) || Entity.EditPartialView || Entity.CreatePartialView;
string createPart = Entity.CreatePartialView ? ", part = true" : string.Empty;
string editPart = Entity.EditPartialView ? ", part = true" : string.Empty;
string detailsPart = Entity.DetailsPartialView ? ", part = true" : string.Empty;

WriteUsingNamespaces(); 
            
            #line default
            #line hidden
            this.Write("@model IEnumerable<");
            
            #line 26 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n@{\r\n    ViewBag.Title = @");
            
            #line 28 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 28 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write(@";

    //Authorization Flags
    bool canUserEdit = ViewBag.canUserEdit;
    bool canUserCreate = ViewBag.canUserCreate;
    bool canUserDelete = ViewBag.canUserDelete;
    bool canSeeRestricted = ViewBag.canSeeRestricted;

    //Records & Pager
    int page = ViewBag.page;
    int totalCount = ViewBag.totalCount;
    int pageSize = ViewBag.pageSize;
    int pageCount = ViewBag.pageCount;

    var title = ");
            
            #line 42 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 42 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write(";\r\n}\r\n<div class=\"row well hidden-print\">\r\n    <div class=\"col-md-8 col-sm-7\">\r\n " +
                    "       <h4>@title</h4>\r\n    </div>\r\n");
            
            #line 48 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(searchable)
    { 
            
            #line default
            #line hidden
            this.Write(@"    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = ""searchForm"" }))
    {
        @Html.Hidden(""page"", page)
        @Html.Hidden(""pageSize"", pageSize)
        <div class=""col-md-4 col-sm-5"">
            @Html.Partial(""_SearchBoxPartial"")
        </div>
    }
");
            
            #line 58 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } 
            
            #line default
            #line hidden
            this.Write("</div>\r\n@if (totalCount > 0)\r\n{\r\n    <div id=\"");
            
            #line 62 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridId));
            
            #line default
            #line hidden
            this.Write("Parent\" class=\"table-responsive\">\r\n        <table id=\"");
            
            #line 63 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridId));
            
            #line default
            #line hidden
            this.Write("\" class=\"table table-striped table-bordered table-hover\">\r\n            <tr>\r\n");
            
            #line 65 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(Entity.IndexViewGeneration == IndexViewGeneration.HtmlTableWithMenuAction) { 
            
            #line default
            #line hidden
            this.Write("                <th class=\"hidden-print\" width=\"20px\">@ActionStrings.Action</th>\r" +
                    "\n");
            
            #line 67 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } 
            
            #line default
            #line hidden
            
            #line 68 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"

foreach (var property in properties) 
{

            
            #line default
            #line hidden
            this.Write("                <th>@Html.DisplayNameFor(model => model.");
            
            #line 72 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")</th>\r\n");
            
            #line 73 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"

} 
            
            #line default
            #line hidden
            
            #line 75 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(Entity.IndexViewGeneration == IndexViewGeneration.HtmlTableWithButtonsAction) { 
            
            #line default
            #line hidden
            this.Write("                <th class=\"hidden-print\">@ActionStrings.Actions</th>\r\n");
            
            #line 77 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } 
            
            #line default
            #line hidden
            this.Write("            </tr>\r\n    @foreach (var item in Model)\r\n    {\r\n                <tr>\r" +
                    "\n");
            
            #line 82 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(Entity.IndexViewGeneration == IndexViewGeneration.HtmlTableWithMenuAction) { 
            
            #line default
            #line hidden
            this.Write(@"                    <td class=""hidden-print"">
                        <div class=""btn-group"">
                            <button type=""button"" title=""@ActionStrings.Action"" class=""btn btn-xs btn-default dropdown-toggle"" data-toggle=""dropdown"" onclick='onActionMenuClick(this)'>
                                <span class=""glyphicon glyphicon-tasks""></span> <span class=""caret""></span>
                            </button>
                            <ul class=""dropdown-menu"" role=""menu"">
                                <li>@Html.ActionLink(ActionStrings.Details, ""Details"", new { id = item.Id");
            
            #line 89 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(detailsPart));
            
            #line default
            #line hidden
            this.Write(" }");
            
            #line 89 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(Entity.DetailsPartialView) { 
            
            #line default
            #line hidden
            this.Write(", new { input_modal = ActionStrings.Details }");
            
            #line 89 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
 } 
            
            #line default
            #line hidden
            this.Write(")</li>\r\n                                @if (canUserEdit)\r\n                      " +
                    "          {\r\n                                    <li>@Html.ActionLink(ActionStri" +
                    "ngs.Edit, \"Edit\", new { id = item.Id");
            
            #line 92 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(editPart));
            
            #line default
            #line hidden
            this.Write(" }");
            
            #line 92 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(Entity.EditPartialView) { 
            
            #line default
            #line hidden
            this.Write(", new { input_modal = ");
            
            #line 92 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".Edit");
            
            #line 92 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(" }");
            
            #line 92 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
 } 
            
            #line default
            #line hidden
            this.Write(")</li>\r\n                                }\r\n");
            
            #line 94 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"

if (collectionProperties.Any()) 
{
    int collNr = 0;

            
            #line default
            #line hidden
            this.Write(@"                                @if (canUserDelete)
                                {
                                    <li>
                                        <a href=""#deleteConfirm"" data-toggle=""modal"" onclick=""setDelete('<b>@Html.Encode(item.");
            
            #line 102 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DisplayMember));
            
            #line default
            #line hidden
            this.Write(")</b>\', @item.");
            
            #line 102 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pKey));
            
            #line default
            #line hidden
            this.Write(");\">\r\n                                            @ActionStrings.Delete\r\n        " +
                    "                                </a>\r\n                                    </li>\r" +
                    "\n                                }\r\n");
            
            #line 107 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write(@"                                @if (canUserDelete)
                                {
                                    <li>
                                        <a href=""#deleteConfirm"" data-toggle=""modal"" onclick=""setDelete('<b>@Html.Encode(item.");
            
            #line 111 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DisplayMember));
            
            #line default
            #line hidden
            this.Write(")</b>\', @item.");
            
            #line 111 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pKey));
            
            #line default
            #line hidden
            this.Write(");\">\r\n                                            @ActionStrings.Delete\r\n        " +
                    "                                </a>\r\n                                    </li>\r" +
                    "\n                                }\r\n");
            
            #line 116 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
 } 
            
            #line default
            #line hidden
            
            #line 117 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if (entitiesThisForCreate.Any()) 
    { 
            
            #line default
            #line hidden
            this.Write("                                @if (canUserCreate)\r\n                            " +
                    "    {\r\n                                <li class=\"divider\"></li>\r\n");
            
            #line 122 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
    foreach (var entity in entitiesThisForCreate)
        {
            
            #line default
            #line hidden
            this.Write("                                <li>@Html.ActionLink(");
            
            #line 124 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".Add");
            
            #line 124 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(", \"Create\", \"");
            
            #line 124 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("\", new { ");
            
            #line 124 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.StrongDependedForeignKey.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = item.Id");
            
            #line 124 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(createPart));
            
            #line default
            #line hidden
            this.Write(" }, ");
            
            #line 124 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(Entity.CreatePartialView) { 
            
            #line default
            #line hidden
            this.Write("new { input_modal = ");
            
            #line 124 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".Add");
            
            #line 124 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" }");
            
            #line 124 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("null");
            
            #line 124 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
 } 
            
            #line default
            #line hidden
            this.Write(")</li>\r\n                                <li>@Html.ActionLink(");
            
            #line 125 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 125 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(", \"Index\", \"");
            
            #line 125 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("\", new { ");
            
            #line 125 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.StrongDependedForeignKey.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = item.Id");
            
            #line 125 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(createPart));
            
            #line default
            #line hidden
            this.Write(" }, null)</li>\r\n");
            
            #line 126 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
        } 
            
            #line default
            #line hidden
            this.Write("                                }\r\n");
            
            #line 128 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } 
            
            #line default
            #line hidden
            this.Write("                        </ul>\r\n                    </div>\r\n                </td>\r" +
                    "\n");
            
            #line 132 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } 
            
            #line default
            #line hidden
            
            #line 133 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"

foreach (var property in properties) 
{
    if(property.PropertyDefinition is CollectionProperty)
    {

            
            #line default
            #line hidden
            this.Write("                <td>@item.");
            
            #line 139 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(".Count</td>\r\n");
            
            #line 140 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } else if(property.PropertyDefinition.IsTypeNumeric() || property.PropertyDefinition.IsTypeDateTime()) { 
            
            #line default
            #line hidden
            this.Write("                <td align=\"right\">@Html.DisplayFor(modelItem => item.");
            
            #line 141 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")</td>\r\n");
            
            #line 142 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                <td>@Html.DisplayFor(modelItem => item.");
            
            #line 143 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")</td>\r\n");
            
            #line 144 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  }
} 
            
            #line default
            #line hidden
            
            #line 146 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(Entity.IndexViewGeneration == IndexViewGeneration.HtmlTableWithButtonsAction) { 
            
            #line default
            #line hidden
            this.Write("                    <td class=\"hidden-print\">\r\n                        <a href=\'@" +
                    "Url.Action(\"Details\", new { id = item.Id");
            
            #line 148 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(detailsPart));
            
            #line default
            #line hidden
            this.Write(" })\'");
            
            #line 148 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(Entity.DetailsPartialView) { 
            
            #line default
            #line hidden
            this.Write(" input-modal=\'@ActionStrings.Details\' ");
            
            #line 148 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" title=\"@ActionStrings.Details\"><span class=\"glyphicon glyphicon-new-window ml5\">" +
                    "</span></a>\r\n                        @if (canUserEdit)\r\n                        " +
                    "{\r\n                            <a href=\'@Url.Action(\"Edit\", new { id = item.Id");
            
            #line 151 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(editPart));
            
            #line default
            #line hidden
            this.Write(" })\'");
            
            #line 151 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(Entity.EditPartialView) { 
            
            #line default
            #line hidden
            this.Write(" input-modal=\'@");
            
            #line 151 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".Edit");
            
            #line 151 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write("\' ");
            
            #line 151 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@" title=""@ActionStrings.Edit""><span class=""glyphicon glyphicon-edit ml5""></span></a>
                        }
                        @if (canUserDelete)
                        {
                            <a href=""#deleteConfirm"" data-toggle=""modal"" title=""@ActionStrings.Delete"" onclick=""setDelete('<b>@Html.Encode(item.");
            
            #line 155 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DisplayMember));
            
            #line default
            #line hidden
            this.Write(")</b>\', @item.");
            
            #line 155 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pKey));
            
            #line default
            #line hidden
            this.Write(");\" >\r\n                                <span class=\"glyphicon glyphicon-trash ml5" +
                    "\"></span>\r\n                                </a>\r\n                        }\r\n    " +
                    "                </td>\r\n");
            
            #line 160 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } 
            
            #line default
            #line hidden
            this.Write("            </tr>\r\n    }\r\n        </table>\r\n    </div>\r\n}\r\nelse\r\n{\r\n    <h4>@Mess" +
                    "ageStrings.NoResults!</h4>\r\n}\r\n@Html.Partial(\"");
            
            #line 170 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MvcPartialPager.ViewName));
            
            #line default
            #line hidden
            this.Write("\")\r\n@Html.Partial(\"_MessageBoxPartial\")\r\n@section scripts{\r\n");
            
            #line 173 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(Entity.EditPartialView || Entity.CreatePartialView) { 
            
            #line default
            #line hidden
            this.Write("    @Scripts.Render(\"~/bundles/jqueryval\")\r\n");
            
            #line 175 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } 
            
            #line default
            #line hidden
            this.Write("    @Html.Partial(\"");
            
            #line 176 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MvcPartialIndexScripts.ViewName));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 176 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("\") @* Controller\'s name *@\r\n");
            
            #line 177 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(hasScript) { 
            
            #line default
            #line hidden
            this.Write("    <script type=\"text/javascript\">\r\n");
            
            #line 179 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } 
            
            #line default
            #line hidden
            
            #line 180 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(Entity.EditPartialView || Entity.CreatePartialView) { 
            
            #line default
            #line hidden
            this.Write(@"        (function () {
            $('a[input-modal]').on('click', function () {
                showMessageBox('@MessageStrings.Loading...', '@MessageStrings.PleaseWait.', false);
                var title = $(this).attr(""input-modal"");
                $('#dataInputBody').load(this.href, function () {
                    hideMessageBox();
                    if (title != null || title != '') {
                        $('#dataInputTitle').html(title);
                    }
                    var inputForm = document.getElementById('dataInputForm');
                    if (isNaN(inputForm)) {
                        $('#dataInputSubmit').show();
                    }
                    else {
                        $('#dataInputSubmit').hide();
                    }
                    $('#dataInputModal').modal('show');
                });
                return false;
            });
        }());
");
            
            #line 202 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } 
            
            #line default
            #line hidden
            
            #line 203 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(Entity.IndexViewGeneration == IndexViewGeneration.HtmlTableWithMenuAction) { 
            
            #line default
            #line hidden
            this.Write("        function onActionMenuClick(menuBtn) {\r\n            setTimeout(function ()" +
                    " {\r\n                var menuHeight = 160;\r\n                var rectMenu = menuBt" +
                    "n.getBoundingClientRect();\r\n                var rectGrid = document.getElementBy" +
                    "Id(\"");
            
            #line 208 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridId));
            
            #line default
            #line hidden
            this.Write("\").getBoundingClientRect();\r\n                var diffY = rectGrid.bottom - rectMe" +
                    "nu.bottom - menuHeight;\r\n\r\n                if (diffY < 0) {\r\n                   " +
                    " var viewport = $(\'#");
            
            #line 212 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(gridId));
            
            #line default
            #line hidden
            this.Write("Parent\');\r\n                    var viewportScroll = viewport.scrollTop();\r\n      " +
                    "              viewport.scrollTop((diffY * -1) + viewportScroll);\r\n              " +
                    "  }\r\n            }, 250);\r\n        }\r\n");
            
            #line 218 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } 
            
            #line default
            #line hidden
            
            #line 219 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  if(hasScript) { 
            
            #line default
            #line hidden
            this.Write("    </script>\r\n");
            
            #line 221 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcIndexView.tt"
  } 
            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
