// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.AspNetMvc.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcPartialPager.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class MvcPartialPager : AbstractMvcView
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcPartialPager.tt"
 
WriteUsingNamespaces(); 
            
            #line default
            #line hidden
            this.Write("@{\r\n    Layout = null;\r\n    int page = ViewBag.page;\r\n    int totalCount = ViewBa" +
                    "g.totalCount;\r\n    int pageSize = ViewBag.pageSize;\r\n    int pageCount = ViewBag" +
                    ".pageCount;\r\n    int pagers = pageCount > 10 ? 10 : pageCount;\r\n    int pagerSta" +
                    "rt = page > 5 ? page - (pagers / 2) : 1;\r\n    if ((pagerStart + pagers) > pageCo" +
                    "unt)\r\n    {\r\n        pagerStart = pageCount - pagers + 1;\r\n    }\r\n}\r\n@if (pageCo" +
                    "unt > 1)\r\n{\r\n<nav>\r\n    <ul class=\"pagination\">\r\n        @if (page == 1)\r\n      " +
                    "  {\r\n            <li class=\"disabled\">\r\n                <a aria-label=\"Previous\"" +
                    ">\r\n                    <span aria-hidden=\"true\">&laquo;</span>\r\n                " +
                    "</a>\r\n            </li>\r\n            <li class=\"disabled\">\r\n                <a a" +
                    "ria-label=\"Previous\">\r\n                    <span aria-hidden=\"true\">&lsaquo;</sp" +
                    "an>\r\n                </a>\r\n            </li>\r\n        }\r\n        else\r\n        {" +
                    "\r\n            <li>\r\n                <a href=\"#\" aria-label=\"FirstPage\" onclick=\"" +
                    "getPagedData(1)\">\r\n                    <span aria-hidden=\"true\">&laquo;</span>\r\n" +
                    "                </a>\r\n            </li>\r\n            <li>\r\n                <a hr" +
                    "ef=\"#\" aria-label=\"Previous\" onclick=\"getPagedData(@(page - 1))\">\r\n             " +
                    "       <span aria-hidden=\"true\">&lsaquo;</span>\r\n                </a>\r\n         " +
                    "   </li>\r\n        }\r\n        @for (int i = pagerStart; i < (pagerStart + pagers)" +
                    "; i++)\r\n        {\r\n            if (page == i)\r\n            {\r\n                <l" +
                    "i class=\"active\"><a>@i <span class=\"sr-only\">(current)</span></a></li>\r\n        " +
                    "    }\r\n            else\r\n            {\r\n                <li><a href=\"#\" onclick=" +
                    "\"getPagedData(@i)\">@i</a></li>\r\n            }\r\n        }\r\n        @if (page < pa" +
                    "geCount)\r\n        {\r\n            <li>\r\n                <a href=\"#\" aria-label=\"N" +
                    "ext\" onclick=\"getPagedData(@(page + 1))\">\r\n                    <span aria-hidden" +
                    "=\"true\">&rsaquo;</span>\r\n                </a>\r\n            </li>\r\n            <l" +
                    "i>\r\n                <a href=\"#\" aria-label=\"Next\" onclick=\"getPagedData(@(pageCo" +
                    "unt))\">\r\n                    <span aria-hidden=\"true\">&raquo;</span>\r\n          " +
                    "      </a>\r\n            </li>\r\n        }\r\n        else\r\n        {\r\n            <" +
                    "li class=\"disabled\">\r\n                <a aria-label=\"Next\">\r\n                   " +
                    " <span aria-hidden=\"true\">&rsaquo;</span>\r\n                </a>\r\n            </l" +
                    "i>\r\n            <li class=\"disabled\">\r\n                <a aria-label=\"Next\">\r\n  " +
                    "                  <span aria-hidden=\"true\">&raquo;</span>\r\n                </a>\r" +
                    "\n            </li>\r\n        }\r\n    </ul>\r\n</nav>\r\n}\r\n<script type=\"text/javascri" +
                    "pt\">\r\n    function getPagedData(page) {\r\n        $(\'#page\').val(page);\r\n        " +
                    "$(\'#searchForm\').submit();\r\n    }\r\n    function refreshData() {\r\n        $(\'#sea" +
                    "rchForm\').submit();\r\n    }\r\n</script>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
