// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.AspNetMvc.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcPartialModalDialog.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class MvcPartialModalDialog : AbstractMvcView
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcPartialModalDialog.tt"
 
WriteUsingNamespaces(); 
            
            #line default
            #line hidden
            this.Write("<div class=\"modal fade\" id=\"messageBox\"> @* Message Box *@\r\n    <div class=\"modal" +
                    "-dialog\">\r\n        <div class=\"modal-content\">\r\n            <div class=\"modal-he" +
                    "ader\">\r\n                <button type=\"button\" class=\"close\" data-dismiss=\"modal\"" +
                    " aria-hidden=\"true\">&times;</button>\r\n                <h2 id=\"messageBoxTitle\" c" +
                    "lass=\"modal-title\"></h2>\r\n            </div>\r\n            <div class=\"modal-body" +
                    "\">\r\n                <p id=\"messageBoxText\"></p>\r\n            </div>\r\n           " +
                    " <div class=\"modal-footer\">\r\n                <button id=\"messageBoxCancelButton\"" +
                    " type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">\r\n                  " +
                    "  @ActionStrings.Cancel\r\n                </button>\r\n            </div>\r\n        " +
                    "</div>@* /.modal-content *@\r\n    </div>@* /.modal-dialog *@\r\n</div>@* /.modal *@" +
                    "\r\n\r\n<div class=\"modal fade\" id=\"deleteConfirm\"> @* Delete Confirm Modal *@\r\n    " +
                    "<div class=\"modal-dialog\">\r\n        <div class=\"modal-content\">\r\n            <di" +
                    "v class=\"modal-header\">\r\n                <button type=\"button\" class=\"close\" dat" +
                    "a-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n                <h2 class" +
                    "=\"modal-title\">@ActionStrings.Delete</h2>\r\n            </div>\r\n            <div " +
                    "class=\"modal-body\">\r\n                <p id=\"deleteText\"></p>\r\n            </div>" +
                    "\r\n            <div class=\"modal-footer\">\r\n                <button type=\"button\" " +
                    "class=\"btn btn-default\" data-dismiss=\"modal\">@ActionStrings.Cancel</button>\r\n   " +
                    "             <a id=\"ajxDelete\" style=\"width:70px\" class=\"btn btn-danger\" onclick" +
                    "=\"deleteEntity(0);\">@ActionStrings.Delete</a>\r\n            </div>\r\n        </div" +
                    ">@* /.modal-content *@\r\n    </div>@* /.modal-dialog *@\r\n</div>@* /.modal *@\r\n<di" +
                    "v id=\"busyAnima\" class=\"modal\" style=\"z-index:55000;background-color:#808080;opa" +
                    "city:0.75;\">\r\n    <div style=\"opacity:1.0;position:relative;top:50%;transform:tr" +
                    "anslateY(-50%);width:100%;\">\r\n        <img src=\"~/images/busy.gif\" alt=\"@Message" +
                    "Strings.PleaseWait\" class=\"center-block\" />\r\n    </div>\r\n</div>\r\n<div class=\"mod" +
                    "al fade\" id=\"dataInputModal\"> @* Data Input Modal *@\r\n    <div class=\"modal-dial" +
                    "og modal-lg\">\r\n        <div class=\"modal-content\">\r\n            <div class=\"moda" +
                    "l-header\">\r\n                <button type=\"button\" class=\"close\" data-dismiss=\"mo" +
                    "dal\" aria-hidden=\"true\">&times;</button>\r\n                <h2 id=\"dataInputTitle" +
                    "\" class=\"modal-title\">@ActionStrings.Edit</h2>\r\n            </div>\r\n            " +
                    "<div id=\"dataInputBody\" class=\"modal-body\"></div>\r\n            <div id=\"dataInpu" +
                    "tFooter\" class=\"modal-footer\">\r\n                <button type=\"button\" class=\"btn" +
                    " btn-default\" data-dismiss=\"modal\">@ActionStrings.Cancel</button>\r\n             " +
                    "   <a id=\"dataInputSubmit\" style=\"width:70px\" class=\"btn btn-primary\" onclick=\"s" +
                    "ubmitDataInputForm();\">@ActionStrings.Submit</a>\r\n            </div>\r\n        </" +
                    "div>@* /.modal-content *@\r\n    </div>@* /.modal-dialog *@\r\n</div>@* /.modal *@");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
