// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.AspNetMvc.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using OzzUtils;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class MvcViewSnippets : AbstractMvcView
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 7 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
 
var fkeyProperties = Entity.GetInheritedIncludedProperties().Where(e => (e.InCreateView | e.InEditView) & e.IsForeignKey());
WriteUsingNamespaces(); 
            
            #line default
            #line hidden
            this.Write("\r\n            <!-- Bootstrap navbar nav menu code for ");
            
            #line 11 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write(" -->\r\n            <li class=\"dropdown\">\r\n                <a href=\"#\" class=\"dropd" +
                    "own-toggle\" data-toggle=\"dropdown\">\r\n                    @");
            
            #line 14 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 14 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write("<b class=\"caret\"></b>\r\n                </a>\r\n                <ul class=\"dropdown-" +
                    "menu\">\r\n                    <li>@Html.ActionLink(@");
            
            #line 17 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 17 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write(", \"Index\", \"");
            
            #line 17 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("\")</li>\r\n                    <li>@Html.ActionLink(@");
            
            #line 18 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".Create");
            
            #line 18 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Name));
            
            #line default
            #line hidden
            this.Write(", \"Create\", \"");
            
            #line 18 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.ControllerName));
            
            #line default
            #line hidden
            this.Write("\")</li>\r\n");
            
            #line 19 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
  foreach (var property in fkeyProperties)
    { 
		var foreignEntity = CodeEngine.GetForeignKeyEntity(property);
		if (foreignEntity!=null && foreignEntity!=Entity ){
            
            #line default
            #line hidden
            this.Write("                    <li class=\"divider\"></li>\r\n                    <li>@Html.Acti" +
                    "onLink(@");
            
            #line 24 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 24 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignEntity.Name.Pluralize()));
            
            #line default
            #line hidden
            this.Write(", \"Index\", \"");
            
            #line 24 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignEntity.ControllerName));
            
            #line default
            #line hidden
            this.Write("\")</li>\r\n                    <li>@Html.ActionLink(@");
            
            #line 25 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityResource));
            
            #line default
            #line hidden
            this.Write(".Create");
            
            #line 25 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignEntity.Name));
            
            #line default
            #line hidden
            this.Write(", \"Create\", \"");
            
            #line 25 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignEntity.ControllerName));
            
            #line default
            #line hidden
            this.Write("\")</li>\r\n");
            
            #line 26 "F:\OzzCodeGen\OzzCodeGen\CodeEngines\AspNetMvc\Templates\MvcViewSnippets.tt"
		}
	} 
            
            #line default
            #line hidden
            this.Write("                </ul>\r\n            </li>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
