// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.Templates.Cs
{
    using OzzCodeGen.Definitions;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class CsClassBase : ClassBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            return this.GenerationEnvironment.ToString();
        }
        
        #line 7 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 
protected virtual void WriteUsingNamespaces()
{
    foreach (string n in UsingNamespaces)
    {
        WriteUsingNamespace(n);
    }
} 
        
        #line default
        #line hidden
        
        #line 15 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 
protected virtual void WriteUsingNamespace(string n)
{ 
        
        #line default
        #line hidden
        
        #line 17 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("using ");

        
        #line default
        #line hidden
        
        #line 18 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(n));

        
        #line default
        #line hidden
        
        #line 18 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"

} 
        
        #line default
        #line hidden
        
        #line 21 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 
protected virtual void BeginNamespace()
{ 
	if(!string.IsNullOrEmpty(NamespaceName))
	{
		PushIndent("    ");
        
        #line default
        #line hidden
        
        #line 26 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("namespace ");

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(NamespaceName));

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("\r\n{\r\n");

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
	}
} 
        
        #line default
        #line hidden
        
        #line 31 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 protected virtual void EndNamespace()
{ 
	if(!string.IsNullOrEmpty(NamespaceName))
	{
		PopIndent();
        
        #line default
        #line hidden
        
        #line 35 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("}\r\n");

        
        #line default
        #line hidden
        
        #line 37 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
	}
} 
        
        #line default
        #line hidden
        
        #line 39 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 
protected virtual void WriteFullProperty(string Accessibility, BaseProperty p, bool raisePropertyChanged, string defaultValue = "", string beforeChangeCode = "", string afterChangeCode = "") 
{ 
        
        #line default
        #line hidden
        
        #line 41 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("        ");

        
        #line default
        #line hidden
        
        #line 42 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Accessibility));

        
        #line default
        #line hidden
        
        #line 42 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 42 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(p.TypeName));

        
        #line default
        #line hidden
        
        #line 42 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 42 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));

        
        #line default
        #line hidden
        
        #line 42 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 44 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 WritePropertyGet(p, defaultValue); 
        
        #line default
        #line hidden
        
        #line 45 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 WritePropertySet(p, raisePropertyChanged, beforeChangeCode, afterChangeCode); 
        
        #line default
        #line hidden
        
        #line 45 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("        }\r\n        ");

        
        #line default
        #line hidden
        
        #line 47 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(p.TypeName));

        
        #line default
        #line hidden
        
        #line 47 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(" _");

        
        #line default
        #line hidden
        
        #line 47 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(CamelCase(p.Name)));

        
        #line default
        #line hidden
        
        #line 47 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 } 
        
        #line default
        #line hidden
        
        #line 49 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 
protected virtual void WritePropertySet(BaseProperty p, bool raisePropertyChanged, string beforeChangeCode = "", string afterChangeCode = "") 
{ 
        
        #line default
        #line hidden
        
        #line 51 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("        set\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 54 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 if(raisePropertyChanged) { 
        
        #line default
        #line hidden
        
        #line 54 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("            if (_");

        
        #line default
        #line hidden
        
        #line 55 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(CamelCase(p.Name)));

        
        #line default
        #line hidden
        
        #line 55 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(" == value) return;\r\n");

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 } 
        
        #line default
        #line hidden
        
        #line 57 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 if(!string.IsNullOrEmpty(beforeChangeCode)) { 
        
        #line default
        #line hidden
        
        #line 57 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("                ");

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(beforeChangeCode));

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 59 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 } 
        
        #line default
        #line hidden
        
        #line 59 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("            _");

        
        #line default
        #line hidden
        
        #line 60 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(CamelCase(p.Name)));

        
        #line default
        #line hidden
        
        #line 60 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(" = value;\r\n");

        
        #line default
        #line hidden
        
        #line 61 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 if(raisePropertyChanged) { 
        
        #line default
        #line hidden
        
        #line 61 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("            RaisePropertyChanged(\"");

        
        #line default
        #line hidden
        
        #line 62 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));

        
        #line default
        #line hidden
        
        #line 62 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("\");\r\n");

        
        #line default
        #line hidden
        
        #line 63 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 } 
        
        #line default
        #line hidden
        
        #line 64 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 if(!string.IsNullOrEmpty(afterChangeCode)) { 
        
        #line default
        #line hidden
        
        #line 64 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("                ");

        
        #line default
        #line hidden
        
        #line 65 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(afterChangeCode));

        
        #line default
        #line hidden
        
        #line 65 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 66 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 } 
        
        #line default
        #line hidden
        
        #line 66 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("        }\r\n");

        
        #line default
        #line hidden
        
        #line 68 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 } 
        
        #line default
        #line hidden
        
        #line 69 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 
protected virtual void WritePropertyGet(BaseProperty p, string defaultValue = "") 
{ 
        
        #line default
        #line hidden
        
        #line 71 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("        get\r\n        {\r\n");

        
        #line default
        #line hidden
        
        #line 74 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 if(!string.IsNullOrEmpty(defaultValue)) 
	{
		if(p.IsTypeNullable())
		{ 
        
        #line default
        #line hidden
        
        #line 77 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("            if (_");

        
        #line default
        #line hidden
        
        #line 78 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(CamelCase(p.Name)));

        
        #line default
        #line hidden
        
        #line 78 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(" == null) _");

        
        #line default
        #line hidden
        
        #line 78 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(CamelCase(p.Name)));

        
        #line default
        #line hidden
        
        #line 78 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(" = ");

        
        #line default
        #line hidden
        
        #line 78 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(defaultValue));

        
        #line default
        #line hidden
        
        #line 78 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 79 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
		}
		else if (p.IsTypeString())
        { 
        
        #line default
        #line hidden
        
        #line 81 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("            if (string.IsNullOrEmpty(_");

        
        #line default
        #line hidden
        
        #line 82 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(CamelCase(p.Name)));

        
        #line default
        #line hidden
        
        #line 82 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(")) _");

        
        #line default
        #line hidden
        
        #line 82 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(CamelCase(p.Name)));

        
        #line default
        #line hidden
        
        #line 82 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(" = ");

        
        #line default
        #line hidden
        
        #line 82 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(defaultValue));

        
        #line default
        #line hidden
        
        #line 82 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 83 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
		}
	} 
        
        #line default
        #line hidden
        
        #line 84 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write("            return _");

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(CamelCase(p.Name)));

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
this.Write(";\r\n        }\r\n");

        
        #line default
        #line hidden
        
        #line 87 "C:\Users\ozalp\source\repos\OzzCodeGen\OzzCodeGen\Templates\Cs\CsClassBase.tt"
 } 
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
