using System.Collections.Generic;
using OzzUtils;
using System.ComponentModel;
using System.Xml.Serialization;

namespace OzzCodeGen.Definitions
{
    public abstract class BaseProperty : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void RaisePropertyChanged(string propertyName)
        {
            if (!string.IsNullOrEmpty(propertyName) && PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Name of the property
        /// </summary>
        public string Name
        {
            get { return name; }
            set
            {
                if (name == value) return;
                name = value != null ? value.Replace(" ", "") : string.Empty;
                if (string.IsNullOrEmpty(DisplayName))
                {
                    DisplayName = name.PascalCaseToTitleCase();
                }
                RaisePropertyChanged("Name");
            }
        }
        private string name;

        public string Comment
        {
            get { return _comment; }
            set
            {
                if (_comment == value) return;
                _comment = value;
                RaisePropertyChanged("comment");
            }
        }
        string _comment;


        /// <summary>
        /// Display order for UI
        /// </summary>
        public int DisplayOrder
        {
            get { return displayOrder; }
            set
            {
                if (displayOrder == value) return;
                displayOrder = value;
                RaisePropertyChanged("DisplayOrder");
            }
        }
        private int displayOrder;
        

        /// <summary>
        /// Display text for UI
        /// </summary>
        public string DisplayName
        {
            get
            {
                if (string.IsNullOrEmpty(displayName))
                {
                    displayName = Name.PascalCaseToTitleCase();
                }
                return displayName;
            }
            set
            {
                if (displayName == value) return;
                displayName = value;
                RaisePropertyChanged("DisplayName");
            }
        }
        string displayName;

        public bool Editable
        {
            get { return _editable; }
            set
            {
                if (_editable == value) return;
                _editable = value;
                RaisePropertyChanged("Editable");
            }
        }
        private bool _editable;

        /// <summary>
        /// Type name of the property
        /// </summary>
        public string TypeName
        {
            get { return typeName; }
            set
            {
                if (typeName == value) return;
                typeName = value;
                RaisePropertyChanged("TypeName");
            }
        }
        private string typeName;

        /// <summary>
        /// Type name of the property in the source
        /// </summary>
        public string SourceTypeName
        {
            get { return _sourceTypeName; }
            set
            {
                if (_sourceTypeName == value) return;
                _sourceTypeName = value;
                RaisePropertyChanged("SourceTypeName");
            }
        }
        private string _sourceTypeName;
        
        /// <summary>
        /// If the value computed or generated by client application retuns true
        /// </summary>
        public bool IsClientComputed
        {
            get { return _isClientComputed; }
            set
            {
                if (_isClientComputed == value) return;
                _isClientComputed = value;
                RaisePropertyChanged("IsClientComputed");
            }
        }
        bool _isClientComputed;

        /// <summary>
        /// If the value computed or generated by server application retuns true
        /// </summary>
        public bool IsServerComputed
        {
            get { return _isServerComputed; }
            set
            {
                if (_isServerComputed == value) return;
                _isServerComputed = value;
                RaisePropertyChanged("IsServerComputed");
            }
        }
        bool _isServerComputed;

        /// <summary>
        /// If the value computed or generated by dabatbase retuns true
        /// </summary>
        public bool IsStoreGenerated
        {
            get { return isStoreGenerated; }
            set
            {
                if (isStoreGenerated == value) return;
                isStoreGenerated = value;
                RaisePropertyChanged("IsStoreGenerated");
            }
        }
        private bool isStoreGenerated;

        public bool UiVisible
        {
            get { return _uiVisible; }
            set
            {
                if (_uiVisible == value) return;
                _uiVisible = value;
                RaisePropertyChanged("UiVisible");
            }
        }
        private bool _uiVisible;


        public override string ToString()
        {
            return string.Format("{0} [{1}]", Name, TypeName);
        }

        public abstract DefinitionType DefinitionType { get; }

        
        [XmlIgnore]
        public EntityDefinition EntityDefinition { get; set; }

        [XmlIgnore]
        public List<string> UsableTypeNames
        {
            get
            {
                if (_usableTypeNames == null)
                    _usableTypeNames = GetUsableTypeNames();
                return _usableTypeNames;
            }
        }
        List<string> _usableTypeNames;

        #region Utility Methods
        public abstract List<string> GetUsableTypeNames();

        public abstract bool IsTypeNullable();

        public string GetNullableTypeName()
        {
            return IsTypeNullable() ? TypeName : TypeName + "?";
        }

        public static bool IsTypeNullable(string type)
        {
            if (type.ToLowerInvariant().Contains("nullable") ||
                type.Trim().EndsWith("?"))
                return true;

            if (IsTypeBoolean(type) || IsTypeDateTime(type) ||
                IsTypeGuid(type) || IsTypeNumeric(type) || IsTypeString(type))
            {
                return false;
            }
            else //demekki object type
            {
                return true;
            }
        }

        public static bool IsTypeSimple(BaseProperty p)
        {
            return IsTypeNumeric(p) || IsTypeString(p) ||
                IsTypeGuid(p) || IsTypeDateTime(p) ||
                IsTypeBoolean(p);
        }

        public static bool IsTypeSimple(string typeName)
        {
            return IsTypeNumeric(typeName) || IsTypeString(typeName) ||
                IsTypeGuid(typeName) || IsTypeDateTime(typeName) ||
                IsTypeBoolean(typeName);
        }

        public abstract bool IsTypeNumeric();

        public static bool IsTypeNumeric(BaseProperty p)
        {
            return p.IsTypeNumeric();
        }
        public static bool IsTypeNumeric(string typeName)
        {
            return typeName.ToLowerInvariant().Contains("int") || typeName.Contains("uint") ||
                 typeName.Contains("short") || typeName.Contains("ushort") ||
                 typeName.Contains("ulong") || typeName.Contains("long") ||
                 typeName.Contains("decimal") || typeName.Contains("float") || typeName.Contains("double") ||
                 typeName.Contains("byte") || typeName.Contains("sbyte");
        }


        public abstract bool IsTypeDateTime();
        public static bool IsTypeDateTime(BaseProperty p)
        {
            return p.IsTypeDateTime();
        }
        public static bool IsTypeDateTime(string typeName)
        {
            return typeName.ToLowerInvariant().Contains("datetime");
        }


        public abstract bool IsTypeBoolean();

        public static bool IsTypeBoolean(BaseProperty p)
        {
            return p.IsTypeBoolean();
        }
        public static bool IsTypeBoolean(string typeName)
        {
            return typeName.ToLowerInvariant().Contains("bool");
        }


        public abstract bool IsTypeString();

        public static bool IsTypeString(BaseProperty p)
        {
            return p.IsTypeString();
        }

        public static bool IsTypeString(string typeName)
        {
            return typeName.ToLowerInvariant().Contains("string");
        }

        public static bool IsTypeCollection(string typeName)
        {
            //TODO: detect for more collection types
            return typeName.StartsWith("ICollection<");
        }


        public abstract bool IsTypeGuid();

        public static bool IsTypeGuid(BaseProperty p)
        {
            return p.IsTypeGuid();
        }
        public static bool IsTypeGuid(string type)
        {
            return type.ToLowerInvariant().Contains("guid");
        }

        public virtual BaseProperty Clone()
        {
            var clone = BaseProperty.CreatePropertyDefinition(DefinitionType, Name);
            clone.IsStoreGenerated = IsStoreGenerated;
            clone.Comment = this.Comment;
            clone.DisplayName = this.DisplayName;
            clone.DisplayOrder = this.DisplayOrder;
            clone.Editable = this.Editable;
            clone.IsClientComputed = this.IsClientComputed;
            clone.IsServerComputed = this.IsServerComputed;
            clone.SourceTypeName = this.SourceTypeName;
            clone.UiVisible = this.UiVisible;

            return clone;
        }

        public static BaseProperty CreatePropertyDefinition(string typeName)
        {
            BaseProperty property;
            if (IsTypeSimple(typeName))
            {
                if (IsTypeString(typeName))
                {
                    property = new StringProperty();
                }
                else
                {
                    property = new SimpleProperty();
                }
            }
            else if (IsTypeCollection(typeName))
            {
                property = new CollectionProperty();
            }
            else
            {
                property = new ComplexProperty();
            }

            property.TypeName = typeName;
            return property;
        }

        public static BaseProperty CreatePropertyDefinition(string typeName, string propertyName)
        {
            BaseProperty property = CreatePropertyDefinition(typeName);
            property.Name = propertyName;
            return property;
        }

        public static BaseProperty CreatePropertyDefinition(string typeName, string propertyName, bool isStoreGenerated)
        {
            BaseProperty property = CreatePropertyDefinition(typeName, propertyName);
            property.IsStoreGenerated = isStoreGenerated;
            return property;
        }

        public static BaseProperty CreatePropertyDefinition(DefinitionType propertyType, string propertyName)
        {
            BaseProperty property;
            switch (propertyType)
            {
                case DefinitionType.Collection:
                    property = new CollectionProperty();
                    break;

                case DefinitionType.Complex:
                    property = new ComplexProperty();
                    break;

                case DefinitionType.DateTime:
                    property = new SimpleProperty();
                    property.TypeName = "DateTime";
                    break;

                case DefinitionType.Simple:
                    property = new SimpleProperty();
                    break;

                case DefinitionType.String:
                    property = new StringProperty();
                    property.TypeName = "string";
                    break;

                default:
                    property = new SimpleProperty();
                    break;
            }

            property.Name = propertyName;
            property.Editable = true;
            property.UiVisible = true;

            return property;
        }
        #endregion
    }
}
