// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.CodeEngines.CsSqliteRepository.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using OzzCodeGen.Definitions;
    using OzzCodeGen.CodeEngines;
    using OzzCodeGen.Templates.Cs;
    using OzzUtils;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class BaseCSharpSqliteRepositoryTemplate : AbstractTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            return this.GenerationEnvironment.ToString();
        }
        
        #line 10 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
 
public void WriteColumnsAndParameters(IEnumerable<SqliteRepositoryPropertySetting> columns, SqliteRepositoryPropertySetting? pkey = null)
{
    PushIndent("    ");
    PushIndent("    ");
    if (pkey != null)
        WriteSingleColumnAndParameter(pkey);
    foreach(var col in columns) {
        WriteSingleColumnAndParameter(col);
    }
    PopIndent();
    PopIndent();
} 
        
        #line default
        #line hidden
        
        #line 23 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
 
public void WriteSingleColumnAndParameter(SqliteRepositoryPropertySetting col)
{
    if(col.IsNullableString ){
        
        #line default
        #line hidden
        
        #line 26 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write("    AddNullableTextParameter(command, \"@");

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(col.Name.ToCamelCase()));

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write("\", ");

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));

        
        #line default
        #line hidden
        
        #line 27 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 28 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
 } else if(col.IsBoolean) { 
        
        #line default
        #line hidden
        
        #line 28 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write("    command.Parameters.AddWithValue(\"@");

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(col.Name.ToCamelCase()));

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write("\", ");

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));

        
        #line default
        #line hidden
        
        #line 29 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(" ? 1 : 0);\r\n");

        
        #line default
        #line hidden
        
        #line 30 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
 } else {
        
        #line default
        #line hidden
        
        #line 30 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write("    command.Parameters.AddWithValue(\"@");

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(col.Name.ToCamelCase()));

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write("\", ");

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(EntitySetting.Name.ToCamelCase()));

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));

        
        #line default
        #line hidden
        
        #line 31 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 32 "C:\Users\ozalp\Source\Repos\OzzCodeGen\OzzCodeGen\CodeEngines\CsSqliteRepository\Templates\BaseCSharpSqliteRepositoryTemplate.tt"
 }
} 
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
