// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzzCodeGen.AppEngines.Storage.Templates.MsSql
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class CreateTSqlTable : AbstractStorageTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("SET ANSI_NULLS ON\r\nGO\r\nSET QUOTED_IDENTIFIER ON\r\nGO\r\nCREATE TABLE [");
            
            #line 11 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 11 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("](\r\n");
            
            #line 12 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
    if(TableDefinition.PrimaryKeyColumn != null) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 13 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.GetPrimaryKeyDeclaration()));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 14 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
  }
	else { 
            
            #line default
            #line hidden
            this.Write("\t--No Primary Key defined!\r\n");
            
            #line 17 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
  } 
            
            #line default
            #line hidden
            
            #line 18 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
    var columns = TableDefinition.UseInheritance ?
			TableDefinition.Properties.Where(c => c.PrimaryKey == false & c.Exclude == false) :
			TableDefinition.GetColumnList().Where(c => c.PrimaryKey == false & c.Exclude == false);

      foreach (var column in columns)
      {
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 24 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.GetColumnDeclaration(column)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 25 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
    } 
            
            #line default
            #line hidden
            
            #line 26 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
    if(TableDefinition.ModifyTrack) 
	  { 
		foreach (var column in AppEngine.GetModifyTrackColumns())
		{
			if(columns.Where(c=>c.Name.Equals(column.Name)).Count()==0)
			{
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 32 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.GetColumnDeclaration(column)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 33 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
			}
		}
      } 
            
            #line default
            #line hidden
            
            #line 36 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
    if(TableDefinition.PrimaryKeyColumn != null) { 
            
            #line default
            #line hidden
            this.Write("  CONSTRAINT [PK_");
            
            #line 37 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("] PRIMARY KEY CLUSTERED ([");
            
            #line 37 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.PrimaryKeyColumn.Name));
            
            #line default
            #line hidden
            this.Write("] ASC)\r\n  WITH (PAD_INDEX  = OFF,\r\n    STATISTICS_NORECOMPUTE  = OFF,\r\n    IGNORE" +
                    "_DUP_KEY = OFF,\r\n    ALLOW_ROW_LOCKS  = ON,\r\n    ALLOW_PAGE_LOCKS  = ON)\r\n  ON [" +
                    "PRIMARY]) ON [PRIMARY]\r\n");
            
            #line 44 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
  } 
            
            #line default
            #line hidden
            this.Write("Go\r\n");
            
            #line 46 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
	foreach (var column in columns.Where(c=>c.Indexed))
    {
            
            #line default
            #line hidden
            this.Write("Create Nonclustered Index [idx_");
            
            #line 48 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 48 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("] On [");
            
            #line 48 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 48 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("]([");
            
            #line 48 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("] ");
            
            #line 48 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
 if(column.SortDesc) {
            
            #line default
            #line hidden
            this.Write("Desc");
            
            #line 48 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
} else {
            
            #line default
            #line hidden
            this.Write("Asc");
            
            #line 48 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
 } 
            
            #line default
            #line hidden
            this.Write(")\r\nGo\r\n");
            
            #line 50 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
  } 
            
            #line default
            #line hidden
            
            #line 51 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
    if(TableDefinition.Name == "EntityUpdate" && columns.Where(c => c.Name == "UpdateDate").Any()) { 
            
            #line default
            #line hidden
            this.Write("\r\nCREATE PROCEDURE EntityUpdated\r\n\t@EntityTypeId    int\r\nAS\r\nBEGIN\r\n\tUpdate [");
            
            #line 57 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 57 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("] Set [UpdateDate] = GETDATE()\r\n\tWhere [");
            
            #line 58 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.SchemaName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 58 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.TableName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 58 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableDefinition.PrimaryKeyColumn.Name));
            
            #line default
            #line hidden
            this.Write("] = @EntityTypeId\r\nEND\r\nGo\r\n");
            
            #line 61 "F:\OzzCodeGen\OzzCodeGen\AppEngines\Storage\Templates\MsSql\CreateTSqlTable.tt"
  } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
